/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ViskoRental.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.ViskoRental.controller.EmployeeRegistrationController;
import lk.ijse.ViskoRental.model.Employee;

/**
 *
 * @author hp
 */
public class AdminEmployeeRegistrationView extends javax.swing.JFrame {

    private int selectedRow;

    /**
     * Creates new form EmployeeRegistration
     */
    public AdminEmployeeRegistrationView() {
        initComponents();
        setLocationRelativeTo(null);
        loadAllEmployee();
        generateEmployeeId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmployee = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        txtcontact = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaddress = new javax.swing.JTextPane();
        jButton18 = new javax.swing.JButton();
        btnSarch = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnRefersh = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnClientRegistration = new javax.swing.JButton();
        btnRepair = new javax.swing.JButton();
        btnItemDetails = new javax.swing.JButton();
        btnUserDetails = new javax.swing.JButton();
        btnPaymentDetails = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnClientPayment = new javax.swing.JButton();
        btnAddorder = new javax.swing.JButton();
        btnOrderDetails1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 71, 135));
        jLabel2.setText("Employee Registration");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 290, 50));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Employee Contact Number");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 250, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Employee ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 140, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Employee Name");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 170, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Employee Address");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 190, -1));

        tblEmployee.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tblEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee ID", "Employee Name", "Employee Contact Number", "Employee Address"
            }
        ));
        tblEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmployeeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmployee);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 1020, 150));

        btnAdd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_48px.png"))); // NOI18N
        btnAdd.setText("ADD ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 130, 50));

        txtid.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 310, 40));

        txtcontact.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactActionPerformed(evt);
            }
        });
        jPanel1.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 310, 40));

        txtname.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 440, 40));

        txtaddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane2.setViewportView(txtaddress);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 310, 70));

        jButton18.setBackground(new java.awt.Color(0, 51, 255));
        jButton18.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jButton18.setForeground(java.awt.Color.white);
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/back_arrow_48px.png"))); // NOI18N
        jButton18.setText("BACK");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 700, 190, 50));

        btnSarch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSarch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/search_48px.png"))); // NOI18N
        btnSarch.setText("SARCH");
        btnSarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSarchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSarch, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 180, 50));

        btnUpdate.setBackground(new java.awt.Color(230, 126, 34));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/update_user_48px.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 180, 50));

        btnDelete.setBackground(new java.awt.Color(231, 76, 60));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/waste_48px.png"))); // NOI18N
        btnDelete.setText("DELELTE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 180, 50));

        btnRefersh.setBackground(new java.awt.Color(102, 102, 255));
        btnRefersh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRefersh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/sync_48px.png"))); // NOI18N
        btnRefersh.setText("REFRESH");
        btnRefersh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefershActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefersh, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 200, 50));

        btnClear.setBackground(new java.awt.Color(102, 102, 255));
        btnClear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/broom_48px.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 370, 180, 50));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientRegistration.setBackground(java.awt.Color.black);
        btnClientRegistration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientRegistration.setForeground(java.awt.Color.white);
        btnClientRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_40px.png"))); // NOI18N
        btnClientRegistration.setText("Client Registration");
        btnClientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 310, 70));

        btnRepair.setBackground(java.awt.Color.black);
        btnRepair.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnRepair.setForeground(java.awt.Color.white);
        btnRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/maintenance_48px.png"))); // NOI18N
        btnRepair.setText("Repair and Maintain ");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });
        jPanel2.add(btnRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 310, 70));

        btnItemDetails.setBackground(java.awt.Color.black);
        btnItemDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnItemDetails.setForeground(java.awt.Color.white);
        btnItemDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/grinding_machine_48px.png"))); // NOI18N
        btnItemDetails.setText("  Item Details");
        btnItemDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnItemDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 310, 70));

        btnUserDetails.setBackground(java.awt.Color.black);
        btnUserDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnUserDetails.setForeground(java.awt.Color.white);
        btnUserDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_48px.png"))); // NOI18N
        btnUserDetails.setText("User Registration");
        btnUserDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnUserDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 310, 70));

        btnPaymentDetails.setBackground(java.awt.Color.black);
        btnPaymentDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnPaymentDetails.setForeground(java.awt.Color.white);
        btnPaymentDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnPaymentDetails.setText("Payment Details");
        btnPaymentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnPaymentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 310, 70));

        jLabel6.setBackground(new java.awt.Color(72, 219, 251));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/menu_48px.png"))); // NOI18N
        jLabel6.setText("HOME");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 59));

        btnClientPayment.setBackground(java.awt.Color.black);
        btnClientPayment.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientPayment.setForeground(java.awt.Color.white);
        btnClientPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnClientPayment.setText("Client Payment");
        btnClientPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 310, 70));

        btnAddorder.setBackground(java.awt.Color.black);
        btnAddorder.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnAddorder.setForeground(java.awt.Color.white);
        btnAddorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_shopping_cart_48px.png"))); // NOI18N
        btnAddorder.setText("Place Order");
        btnAddorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddorderActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 310, 70));

        btnOrderDetails1.setBackground(java.awt.Color.black);
        btnOrderDetails1.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnOrderDetails1.setForeground(java.awt.Color.white);
        btnOrderDetails1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/order_history_48px.png"))); // NOI18N
        btnOrderDetails1.setText("   Order Details");
        btnOrderDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDetails1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrderDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 310, 70));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(72, 219, 251));
        jLabel7.setFont(new java.awt.Font("Stencil", 3, 50)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Visko Rental");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 680, 59));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientRegistrationActionPerformed
        new AdminClintRegistratoinView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClientRegistrationActionPerformed

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        new AdminRepairDetailsView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnRepairActionPerformed

    private void btnItemDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDetailsActionPerformed
        new AdminItemDetailView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnItemDetailsActionPerformed

    private void btnUserDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserDetailsActionPerformed
         new AdminUserRegitrationView().setVisible(true);
         this.hide();
    }//GEN-LAST:event_btnUserDetailsActionPerformed

    private void btnPaymentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentDetailsActionPerformed
        new AdminPaymentDetailsView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnPaymentDetailsActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        if (txtname.getText().trim().length() > 0) {
            try {
                Employee obj = new EmployeeRegistrationController().getEmployee(txtname.getText().trim());
                if (obj != null) {
                    txtid.setText(obj.getEmployeeId());
                    txtcontact.setText(obj.getEmployeeContact());
                    txtaddress.setText(obj.getEmployeeAddress());
                } else {
                    JOptionPane.showMessageDialog(this, "NO Result Found", "Warring", JOptionPane.ERROR_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Try Again? Enter Employee Name",
                    "PopUp4", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new AdminDashBordView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnClientPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientPaymentActionPerformed
        new AdminClientPaymentView().setVisible(true);
        this.hide();

    }//GEN-LAST:event_btnClientPaymentActionPerformed

    private void btnAddorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddorderActionPerformed
        new AdminPlaceOrderView().setVisible(true);
        this.hide();

    }//GEN-LAST:event_btnAddorderActionPerformed

    private void btnOrderDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDetails1ActionPerformed
        new AdminOrderDetailView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnOrderDetails1ActionPerformed

    private void btnSarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSarchActionPerformed
        String name = txtname.getText();
        try {
            Employee employee = EmployeeRegistrationController.sarchEmployee(name);
            if (employee != null) {
                txtid.setText(employee.getEmployeeId());
                txtcontact.setText(employee.getEmployeeContact());
                txtaddress.setText(employee.getEmployeeAddress());

            } else {
                JOptionPane.showMessageDialog(this, "User not found...");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSarchActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
       Employee employee = new Employee(txtid.getText(),txtname.getText(),txtcontact.getText(),txtaddress.getText());
        try {
            boolean isUpdate = EmployeeRegistrationController.updateEmployee(employee);
            if (isUpdate) {
                JOptionPane.showMessageDialog(this, "Update Success");
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Update fail..");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String name = txtname.getText();
        try {
            boolean isDeleted = EmployeeRegistrationController.deleteEmployee(name);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Deleted..");
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Delete fail..");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefershActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefershActionPerformed
       try {
           ArrayList<Employee> allEmployee = EmployeeRegistrationController.getAllEmployee();
            DefaultTableModel dtm = (DefaultTableModel) tblEmployee.getModel();
            dtm.setRowCount(0);
            for (Employee employee : allEmployee) {
                Object[] rowData = {employee.getEmployeeId(), employee.getEmployeeName(), employee.getEmployeeContact(), employee.getEmployeeAddress()};
                dtm.addRow(rowData);
            }
      } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
           Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRefershActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String empid = txtid.getText();
        String name = txtname.getText();
        String contact = txtcontact.getText();
        String address = txtaddress.getText();
        Employee employee = new Employee(empid,name,contact,address);
        if (!empid.isEmpty() && !name.isEmpty() && !contact.isEmpty() && !address.isEmpty()) {
            try {
                boolean isAdded = EmployeeRegistrationController.employeeAdd(employee);
                if(isAdded){
                JOptionPane.showMessageDialog(this, "Employee Added");
                clear();
                generateEmployeeId();
                loadAllEmployee();
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminEmployeeRegistrationView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (SQLException ex) {
                Logger.getLogger(AdminEmployeeRegistrationView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Try Again?Complete All action",
                    "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void tblEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmployeeMouseClicked
       selectedRow = tblEmployee.getSelectedRow();
        txtid.setText(tblEmployee.getValueAt(selectedRow, 0).toString());
        txtname.setText(tblEmployee.getValueAt(selectedRow, 1).toString());
        txtcontact.setText(tblEmployee.getValueAt(selectedRow, 2).toString());

        txtaddress.setText(tblEmployee.getValueAt(selectedRow, 3).toString());
        
    }//GEN-LAST:event_tblEmployeeMouseClicked

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();;
    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEmployeeRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEmployeeRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEmployeeRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEmployeeRegistrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEmployeeRegistrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddorder;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClientPayment;
    private javax.swing.JButton btnClientRegistration;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnItemDetails;
    private javax.swing.JButton btnOrderDetails1;
    private javax.swing.JButton btnPaymentDetails;
    private javax.swing.JButton btnRefersh;
    private javax.swing.JButton btnRepair;
    private javax.swing.JButton btnSarch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUserDetails;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblEmployee;
    private javax.swing.JTextPane txtaddress;
    private javax.swing.JTextField txtcontact;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        txtid.setText(null);
        txtname.setText(null);
        txtcontact.setText(null);
        txtaddress.setText(null);
      
    }

                                     

    private void loadAllEmployee() {
        try {
           ArrayList<Employee> allEmployee = EmployeeRegistrationController.getAllEmployee();
            DefaultTableModel dtm = (DefaultTableModel) tblEmployee.getModel();
            dtm.setRowCount(0);
            for (Employee employee : allEmployee) {
                Object[] rowData = {employee.getEmployeeId(), employee.getEmployeeName(), employee.getEmployeeContact(), employee.getEmployeeAddress()};
                dtm.addRow(rowData);
            }
      } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
           Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }                                          

    private void generateEmployeeId() {
         try {
            String id = EmployeeRegistrationController.generateEmployeeId();
            txtid.setText(id);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }

    

}
