/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ViskoRental.view;

/**
 *
 * @author hp
 */
public class AdminDashBordView extends javax.swing.JFrame {

    /**
     * Creates new form LogingView
     */
    public AdminDashBordView() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        jPanel2 = new javax.swing.JPanel();
        btnAddorder = new javax.swing.JButton();
        btnRepair = new javax.swing.JButton();
        btnItemDetails = new javax.swing.JButton();
        btnUserRegistration = new javax.swing.JButton();
        btnEmployeeRegistration = new javax.swing.JButton();
        btnOrderDetails = new javax.swing.JButton();
        btnPaymentDetails = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnClientPayment = new javax.swing.JButton();
        btnClientRegistration = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(127, 140, 141));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, -1, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAddorder.setBackground(java.awt.Color.black);
        btnAddorder.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnAddorder.setForeground(java.awt.Color.white);
        btnAddorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_shopping_cart_48px.png"))); // NOI18N
        btnAddorder.setText("Place Order");
        btnAddorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddorderActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 310, 70));

        btnRepair.setBackground(java.awt.Color.black);
        btnRepair.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnRepair.setForeground(java.awt.Color.white);
        btnRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/maintenance_48px.png"))); // NOI18N
        btnRepair.setText("Repair and Maintain ");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });
        jPanel2.add(btnRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 310, 70));

        btnItemDetails.setBackground(java.awt.Color.black);
        btnItemDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnItemDetails.setForeground(java.awt.Color.white);
        btnItemDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/grinding_machine_48px.png"))); // NOI18N
        btnItemDetails.setText("  Item Details");
        btnItemDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnItemDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 310, 70));

        btnUserRegistration.setBackground(java.awt.Color.black);
        btnUserRegistration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnUserRegistration.setForeground(java.awt.Color.white);
        btnUserRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_48px.png"))); // NOI18N
        btnUserRegistration.setText("User Registration");
        btnUserRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnUserRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 310, 70));

        btnEmployeeRegistration.setBackground(java.awt.Color.black);
        btnEmployeeRegistration.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        btnEmployeeRegistration.setForeground(java.awt.Color.white);
        btnEmployeeRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/worker_48px.png"))); // NOI18N
        btnEmployeeRegistration.setText("Employee Registration");
        btnEmployeeRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmployeeRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, 310, 70));

        btnOrderDetails.setBackground(java.awt.Color.black);
        btnOrderDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnOrderDetails.setForeground(java.awt.Color.white);
        btnOrderDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/order_history_48px.png"))); // NOI18N
        btnOrderDetails.setText("   Order Details");
        btnOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrderDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 310, 70));

        btnPaymentDetails.setBackground(java.awt.Color.black);
        btnPaymentDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnPaymentDetails.setForeground(java.awt.Color.white);
        btnPaymentDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnPaymentDetails.setText("Payment Details");
        btnPaymentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnPaymentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 310, 70));

        btnLogout.setBackground(java.awt.Color.black);
        btnLogout.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        btnLogout.setForeground(java.awt.Color.white);
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/go_back_48px.png"))); // NOI18N
        btnLogout.setText("Log Out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 890, 200, 50));

        jLabel1.setBackground(new java.awt.Color(72, 219, 251));
        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/menu_48px.png"))); // NOI18N
        jLabel1.setText("HOME");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 59));

        btnClientPayment.setBackground(java.awt.Color.black);
        btnClientPayment.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientPayment.setForeground(java.awt.Color.white);
        btnClientPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnClientPayment.setText("Client Payment");
        btnClientPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 310, 70));

        btnClientRegistration.setBackground(java.awt.Color.black);
        btnClientRegistration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientRegistration.setForeground(java.awt.Color.white);
        btnClientRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_40px.png"))); // NOI18N
        btnClientRegistration.setText("Client Registration");
        btnClientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 980));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(72, 219, 251));
        jLabel2.setFont(new java.awt.Font("Stencil", 3, 50)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Visko Rental");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 680, 59));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1260, 90));

        mainPanel.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/house-vector-illsutration-home-concept-graphics-illustration-door-two-windows-chimney-76138574.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 800, 600));

        jLabel3.setBackground(new java.awt.Color(51, 51, 255));
        jLabel3.setFont(new java.awt.Font("Britannic Bold", 3, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("HOME");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 620, 220, 40));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/facebook_old_48px.png"))); // NOI18N
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 760, 90, 70));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/whatsapp_48px.png"))); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 760, 60, 70));

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/twitter_48px.png"))); // NOI18N
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 760, 60, 70));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/gmail_48px.png"))); // NOI18N
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 760, 60, 70));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/air_staple_gun_48px.png"))); // NOI18N
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 40, 90, 70));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/angle_grinder_48px.png"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 90, 90, 70));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/toolbox_48px.png"))); // NOI18N
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 160, 90, 70));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/chainsaw_48px.png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 220, 90, 70));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/drill_48px.png"))); // NOI18N
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 290, 90, 70));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/grinding_machine_48px.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 350, 90, 70));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/hand_plane_48px.png"))); // NOI18N
        jPanel4.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 410, 90, 70));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/vise_48px.png"))); // NOI18N
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 470, 90, 70));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/java_48px.png"))); // NOI18N
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 760, 90, 70));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/instagram_48px.png"))); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 760, 60, 70));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 108;
        gridBagConstraints.ipady = 38;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 6, 6);
        mainPanel.add(jPanel4, gridBagConstraints);

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 1260, 880));
        mainPanel.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void btnClientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientRegistrationActionPerformed
         new AdminClintRegistratoinView().setVisible(true);
        this.dispose();
       /* new clientView();
        mainPanel.removeAll();
        mainPanel.add(new clientView());
        mainPanel.repaint();
        mainPanel.revalidate();*/

    }//GEN-LAST:event_btnClientRegistrationActionPerformed

    private void btnClientPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientPaymentActionPerformed
        new AdminClientPaymentView().setVisible(true);
        this.dispose();
       
        /*mainPanel.removeAll();
        mainPanel.add(new ClientPayment());
        mainPanel.repaint();
        mainPanel.revalidate();*/
    }//GEN-LAST:event_btnClientPaymentActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new LogingView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPaymentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentDetailsActionPerformed
        new AdminPaymentDetailsView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPaymentDetailsActionPerformed

    private void btnOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDetailsActionPerformed
        new AdminOrderDetailView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnOrderDetailsActionPerformed

    private void btnEmployeeRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeRegistrationActionPerformed
        new AdminEmployeeRegistrationView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmployeeRegistrationActionPerformed

    private void btnUserRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserRegistrationActionPerformed
        new AdminUserRegitrationView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnUserRegistrationActionPerformed

    private void btnItemDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDetailsActionPerformed
        new AdminItemDetailView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnItemDetailsActionPerformed

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        new AdminRepairDetailsView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRepairActionPerformed

    private void btnAddorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddorderActionPerformed
        new AdminPlaceOrderView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAddorderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashBordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashBordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashBordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashBordView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashBordView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddorder;
    private javax.swing.JButton btnClientPayment;
    private javax.swing.JButton btnClientRegistration;
    private javax.swing.JButton btnEmployeeRegistration;
    private javax.swing.JButton btnItemDetails;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOrderDetails;
    private javax.swing.JButton btnPaymentDetails;
    private javax.swing.JButton btnRepair;
    private javax.swing.JButton btnUserRegistration;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
