/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ViskoRental.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.ViskoRental.controller.ItemDetailsController;
import lk.ijse.ViskoRental.model.Item;

/**
 *
 * @author hp
 */
public class AdminItemDetailView extends javax.swing.JFrame {

    private int selectedRow;

    /**
     * Creates new form AddItemView
     */
    public AdminItemDetailView() {
        initComponents();
        setLocationRelativeTo(null);
        genarateSerialNumber();
        loadAllItem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItem = new javax.swing.JTable();
        txtDay = new javax.swing.JTextField();
        txtserial = new javax.swing.JTextField();
        txtDeposit = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        bntSarch = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnRefersh = new javax.swing.JButton();
        cmbName = new javax.swing.JComboBox<>();
        cmbBrandname = new javax.swing.JComboBox<>();
        btnClear1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnClientRegistration = new javax.swing.JButton();
        btnRepair = new javax.swing.JButton();
        btnUserRegistration = new javax.swing.JButton();
        btnPamentDetails = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnClientPayment = new javax.swing.JButton();
        btnAddorder = new javax.swing.JButton();
        btnOrderDetails = new javax.swing.JButton();
        btnEmployeeRegistration = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(72, 219, 251));
        jLabel2.setFont(new java.awt.Font("Stencil", 3, 50)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Visko Rental");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 680, 59));

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setForeground(new java.awt.Color(255, 253, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(72, 219, 251));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Item Details");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 280, 59));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Serial Number");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 150, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Deposite");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 150, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Item Name");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 110, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Brand Name");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 110, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Qty on Hand");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 110, 30));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Per Day Cost");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 150, 30));

        tbItem.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Brand Name", "Item Name", "Qty on Hand", "Per  Day Cost", "Deposite"
            }
        ));
        tbItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbItem);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 1120, 190));

        txtDay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayActionPerformed(evt);
            }
        });
        jPanel4.add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 310, 40));

        txtserial.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtserial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtserialActionPerformed(evt);
            }
        });
        jPanel4.add(txtserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 310, 40));

        txtDeposit.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepositActionPerformed(evt);
            }
        });
        jPanel4.add(txtDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 310, 40));

        txtqty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        jPanel4.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, 310, 40));

        jButton17.setBackground(new java.awt.Color(0, 51, 255));
        jButton17.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jButton17.setForeground(java.awt.Color.white);
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/back_arrow_48px.png"))); // NOI18N
        jButton17.setText("BACK");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 800, 190, 50));

        btnDelete.setBackground(new java.awt.Color(231, 76, 60));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/waste_48px.png"))); // NOI18N
        btnDelete.setText("DELELTE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 180, 180, 50));

        bntSarch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        bntSarch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/search_48px.png"))); // NOI18N
        bntSarch.setText("SARCH");
        bntSarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSarchActionPerformed(evt);
            }
        });
        jPanel4.add(bntSarch, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 80, 180, 50));

        btnOK.setBackground(new java.awt.Color(153, 153, 255));
        btnOK.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnOK.setForeground(new java.awt.Color(0, 0, 153));
        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/ok_48px.png"))); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel4.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 430, 80, 70));

        btnUpdate.setBackground(new java.awt.Color(230, 126, 34));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/update_user_48px.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 180, 50));

        btnRefersh.setBackground(new java.awt.Color(102, 102, 255));
        btnRefersh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRefersh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/sync_48px.png"))); // NOI18N
        btnRefersh.setText("REFRESH");
        btnRefersh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefershActionPerformed(evt);
            }
        });
        jPanel4.add(btnRefersh, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 710, 200, 50));

        cmbName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chenso", "dril", "Boom", "GasTank", "palanchi" }));
        cmbName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNameActionPerformed(evt);
            }
        });
        jPanel4.add(cmbName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 270, 40));

        cmbBrandname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbBrandname.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excavators", "Backhoe", "Dragline Excavator", "Bulldozers Graders", "Wheel Tractor", "Scraper", "Trenchers", "Loaders", "Tower Cranes" }));
        jPanel4.add(cmbBrandname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 270, 40));

        btnClear1.setBackground(new java.awt.Color(102, 102, 255));
        btnClear1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/broom_48px.png"))); // NOI18N
        btnClear1.setText("CLEAR");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });
        jPanel4.add(btnClear1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 350, 180, 50));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientRegistration.setBackground(java.awt.Color.black);
        btnClientRegistration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientRegistration.setForeground(java.awt.Color.white);
        btnClientRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_40px.png"))); // NOI18N
        btnClientRegistration.setText("Client Registration");
        btnClientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 310, 70));

        btnRepair.setBackground(java.awt.Color.black);
        btnRepair.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnRepair.setForeground(java.awt.Color.white);
        btnRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/maintenance_48px.png"))); // NOI18N
        btnRepair.setText("Repair and Maintain ");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });
        jPanel2.add(btnRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 310, 70));

        btnUserRegistration.setBackground(java.awt.Color.black);
        btnUserRegistration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnUserRegistration.setForeground(java.awt.Color.white);
        btnUserRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_48px.png"))); // NOI18N
        btnUserRegistration.setText("User Registration");
        btnUserRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnUserRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 310, 70));

        btnPamentDetails.setBackground(java.awt.Color.black);
        btnPamentDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnPamentDetails.setForeground(java.awt.Color.white);
        btnPamentDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnPamentDetails.setText("Payment Details");
        btnPamentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPamentDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnPamentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 740, 310, 70));

        jLabel5.setBackground(new java.awt.Color(72, 219, 251));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/menu_48px.png"))); // NOI18N
        jLabel5.setText("HOME");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 59));

        btnClientPayment.setBackground(java.awt.Color.black);
        btnClientPayment.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientPayment.setForeground(java.awt.Color.white);
        btnClientPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnClientPayment.setText("Client Payment");
        btnClientPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, 310, 70));

        btnAddorder.setBackground(java.awt.Color.black);
        btnAddorder.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnAddorder.setForeground(java.awt.Color.white);
        btnAddorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_shopping_cart_48px.png"))); // NOI18N
        btnAddorder.setText("Place Order");
        btnAddorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddorderActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 310, 70));

        btnOrderDetails.setBackground(java.awt.Color.black);
        btnOrderDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnOrderDetails.setForeground(java.awt.Color.white);
        btnOrderDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/order_history_48px.png"))); // NOI18N
        btnOrderDetails.setText("   Order Details");
        btnOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrderDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 310, 70));

        btnEmployeeRegistration.setBackground(java.awt.Color.black);
        btnEmployeeRegistration.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        btnEmployeeRegistration.setForeground(java.awt.Color.white);
        btnEmployeeRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/worker_48px.png"))); // NOI18N
        btnEmployeeRegistration.setText("Employee Registration");
        btnEmployeeRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmployeeRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 310, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1151, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 958, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayActionPerformed

    private void txtserialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtserialActionPerformed
        if (txtserial.getText().trim().length() > 0) {
            try {
                Item obj = new ItemDetailsController().getItem(txtserial.getText().trim());
                if (obj != null) {
                    cmbBrandname.setSelectedItem(obj.getBrand_name());
                    cmbName.setSelectedItem(obj.getItem_name());
                    
                    
                    txtqty.setText(obj.getQty_On_Hand());
                    txtDay.setText(obj.getPer_cost_day() + "");
                    
                    txtDeposit.setText(obj.getDeposite() + "");
                } else {
                    JOptionPane.showMessageDialog(this, "NO Result Found", "Warring", JOptionPane.ERROR_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Try Again? Enter Item Serail number",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtserialActionPerformed

    private void txtDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepositActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void btnClientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientRegistrationActionPerformed
        new AdminClintRegistratoinView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClientRegistrationActionPerformed

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        new AdminRepairDetailsView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnRepairActionPerformed

    private void btnUserRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserRegistrationActionPerformed
        new AdminUserRegitrationView().setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_btnUserRegistrationActionPerformed

    private void btnPamentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPamentDetailsActionPerformed
        new AdminPaymentDetailsView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnPamentDetailsActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new AdminDashBordView().setVisible(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void btnClientPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientPaymentActionPerformed
        new AdminClientPaymentView().setVisible(true);
        this.hide();

    }//GEN-LAST:event_btnClientPaymentActionPerformed

    private void btnAddorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddorderActionPerformed
        new AdminPlaceOrderView().setVisible(true);

    }//GEN-LAST:event_btnAddorderActionPerformed

    private void btnOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDetailsActionPerformed
        new AdminOrderDetailView().setVisible(true);
    }//GEN-LAST:event_btnOrderDetailsActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String serailNO = txtserial.getText();
        String brndName = cmbBrandname.getSelectedItem().toString();
        String itemname = cmbName.getSelectedItem().toString();
        String qty = txtqty.getText();
        double day = Double.parseDouble(txtDay.getText());
        double deposite = Double.parseDouble(txtDeposit.getText());

        Item item = new Item(serailNO, brndName, itemname, qty, day, deposite);
        if (!serailNO.isEmpty() && !brndName.isEmpty() && !itemname.isEmpty()  && !qty.isEmpty()) {

            try {
                boolean isAdded = ItemDetailsController.addItem(item);
                if (isAdded) {
                    JOptionPane.showMessageDialog(this, "User Added");
                    clear();
                    genarateSerialNumber();
                    loadAllItem();
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminItemDetailView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminItemDetailView.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Try Again? Complete All action",
                    "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Item item = new Item(
                txtserial.getText(),
                cmbBrandname.getSelectedItem().toString(),
                cmbName.getSelectedItem().toString(),
               
                txtqty.getText(),
                Double.parseDouble(txtDay.getText()),
               
                Double.parseDouble(txtDeposit.getText())
        );
        try {
            boolean isUpdate = ItemDetailsController.updateItem(item);
            if (isUpdate) {
                JOptionPane.showMessageDialog(this, "Update Success");
                clear();
                genarateSerialNumber();
            } else {
                JOptionPane.showMessageDialog(this, "Update fail..");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefershActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefershActionPerformed
        try {
            ArrayList<Item> allItem = ItemDetailsController.getAllItem();
            DefaultTableModel dtm = (DefaultTableModel) tbItem.getModel();
            dtm.setRowCount(0);
            for (Item item : allItem) {
                Object[] rowData = {
                    item.getSerial_No(), 
                    item.getBrand_name(), 
                    item.getItem_name(), 
                    item.getQty_On_Hand(), 
                    item.getPer_cost_day(), 
                    item.getDeposite()};
                dtm.addRow(rowData);
            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRefershActionPerformed

    private void bntSarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSarchActionPerformed
        String serailno = txtserial.getText();
        try {
            Item item = ItemDetailsController.sarchItem(serailno);
            if (item != null) {
                txtserial.setText(item.getSerial_No());
                cmbBrandname.getSelectedItem().toString();
                cmbName.getSelectedItem().toString();
               
                txtqty.setText(item.getQty_On_Hand());
                txtDay.setText(item.getPer_cost_day() + "");
               
                txtDeposit.setText(item.getDeposite() + "");

            } else {
                JOptionPane.showMessageDialog(this, "User not found...");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bntSarchActionPerformed

    private void tbItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItemMouseClicked
        selectedRow = tbItem.getSelectedRow();

        txtserial.setText(tbItem.getValueAt(selectedRow, 0).toString());
        cmbBrandname.setSelectedItem(tbItem.getValueAt(selectedRow, 1).toString());
        cmbName.setSelectedItem(tbItem.getValueAt(selectedRow, 2).toString());
       
        txtqty.setText(tbItem.getValueAt(selectedRow, 3).toString());
        txtDay.setText(tbItem.getValueAt(selectedRow, 4).toString());
       
        txtDeposit.setText(tbItem.getValueAt(selectedRow,5).toString());


    }//GEN-LAST:event_tbItemMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String serialNO = txtserial.getText();
        try {
            boolean isDeleted = ItemDetailsController.deleteItem(serialNO);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Deleted....");
                clear();
                genarateSerialNumber();
            } else {
                JOptionPane.showMessageDialog(this, "Delete fail...");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        clear();
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void cmbNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNameActionPerformed

    }//GEN-LAST:event_cmbNameActionPerformed

    private void btnEmployeeRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeRegistrationActionPerformed
        new AdminEmployeeRegistrationView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEmployeeRegistrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminItemDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminItemDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminItemDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminItemDetailView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminItemDetailView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSarch;
    private javax.swing.JButton btnAddorder;
    private javax.swing.JButton btnClear1;
    private javax.swing.JButton btnClientPayment;
    private javax.swing.JButton btnClientRegistration;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEmployeeRegistration;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOrderDetails;
    private javax.swing.JButton btnPamentDetails;
    private javax.swing.JButton btnRefersh;
    private javax.swing.JButton btnRepair;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUserRegistration;
    private javax.swing.JComboBox<String> cmbBrandname;
    private javax.swing.JComboBox<String> cmbName;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbItem;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtserial;
    // End of variables declaration//GEN-END:variables

    private void genarateSerialNumber() {
        try {
            String serialNO = ItemDetailsController.generateSerialNumber();
            txtserial.setText(serialNO);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllItem() {
        try {
            ArrayList<Item> allItem = ItemDetailsController.getAllItem();
            DefaultTableModel dtm = (DefaultTableModel) tbItem.getModel();
            dtm.setRowCount(0);
            for (Item item : allItem) {
                Object[] rowData = {
                    item.getSerial_No(),
                    item.getBrand_name(),
                    item.getItem_name(),
                    item.getQty_On_Hand(),
                    item.getPer_cost_day(), 
                    item.getDeposite()};
                dtm.addRow(rowData);
            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void clear() {
        cmbBrandname.setSelectedItem(null);
        cmbName.setSelectedItem(null);
        
       
        txtserial.setText(null);
        txtDeposit.setText(null);
        
        txtDay.setText(null);
        txtqty.setText(null);
    }
}
