/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ViskoRental.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.ViskoRental.controller.ItemDetailsController;
import lk.ijse.ViskoRental.controller.RepairDetailsController;
import lk.ijse.ViskoRental.model.Item;
import lk.ijse.ViskoRental.model.Repair;

/**
 *
 * @author hp
 */
public class AdminRepairDetailsView extends javax.swing.JFrame {

    /**
     * Creates new form RepairDetailsView
     */
    public AdminRepairDetailsView() {
        initComponents();
        setLocationRelativeTo(null);

        genarateRepairID();
        loadAllItem();

        Date date = new Date();
        String formatDate = formatDate(date);
        txtdatetime.setText(formatDate);
        txtRedate.setText(formatDate);
        
        loadAllRepairNumber();
        loadAllRepair();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblRepair = new javax.swing.JTable();
        btnRetun = new javax.swing.JButton();
        cmbSerialno = new javax.swing.JComboBox<>();
        txtRedate = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        txtdatetime = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        txtRepair = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        cmbrepair = new javax.swing.JComboBox<>();
        txtQTY = new javax.swing.JTextField();
        txtSerailno = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        btnRefresh = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnClientRegistration = new javax.swing.JButton();
        btnItemDetails = new javax.swing.JButton();
        btnUserRegistration = new javax.swing.JButton();
        btnPaymentDetails = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnClientPayment = new javax.swing.JButton();
        btnAddorder = new javax.swing.JButton();
        btnOrderDetails2 = new javax.swing.JButton();
        btnEmployeeRegistration = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Added date");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 320, 130, -1));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Repair And Maintain");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Repair Number");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Serial Number");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 140, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText(" Qty");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 100, -1));

        tblRepair.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Repair Number", "Serial Number", "Date/Time", "Qty", "Return Date/Time"
            }
        ));
        jScrollPane2.setViewportView(tblRepair);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 550, 1130, 210));

        btnRetun.setBackground(java.awt.Color.black);
        btnRetun.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRetun.setForeground(java.awt.Color.white);
        btnRetun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/return_48px.png"))); // NOI18N
        btnRetun.setText("Return");
        btnRetun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetunActionPerformed(evt);
            }
        });
        jPanel1.add(btnRetun, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 460, 180, 50));

        cmbSerialno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(cmbSerialno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 170, 40));

        txtRedate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtRedate.setForeground(new java.awt.Color(0, 51, 204));
        txtRedate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRedateActionPerformed(evt);
            }
        });
        jPanel1.add(txtRedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 240, 40));

        jButton17.setBackground(new java.awt.Color(0, 51, 255));
        jButton17.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jButton17.setForeground(java.awt.Color.white);
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/back_arrow_48px.png"))); // NOI18N
        jButton17.setText("BACK");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 840, 190, 50));

        txtdatetime.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtdatetime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdatetimeActionPerformed(evt);
            }
        });
        jPanel1.add(txtdatetime, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 290, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Date/Time");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 80, 130, -1));

        txtqty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        jPanel1.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 180, 40));

        txtRepair.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRepairActionPerformed(evt);
            }
        });
        jPanel1.add(txtRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 220, 40));

        btnAdd.setBackground(java.awt.Color.black);
        btnAdd.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAdd.setForeground(java.awt.Color.white);
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/automation_48px.png"))); // NOI18N
        btnAdd.setText("Add to Rapair");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 180, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1270, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Return Date");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, 130, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Repair Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 160, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Serial Number");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 130, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText(" Qty");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 100, -1));

        cmbrepair.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbrepair.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbrepairItemStateChanged(evt);
            }
        });
        cmbrepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbrepairActionPerformed(evt);
            }
        });
        jPanel1.add(cmbrepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 190, 40));

        txtQTY.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtQTY.setForeground(new java.awt.Color(255, 0, 51));
        txtQTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQTYActionPerformed(evt);
            }
        });
        jPanel1.add(txtQTY, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 470, 220, 40));

        txtSerailno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtSerailno.setForeground(new java.awt.Color(255, 0, 0));
        txtSerailno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerailnoActionPerformed(evt);
            }
        });
        jPanel1.add(txtSerailno, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 210, 40));

        txtdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtdate.setForeground(new java.awt.Color(255, 0, 0));
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 370, 300, 40));

        btnRefresh.setBackground(new java.awt.Color(102, 102, 255));
        btnRefresh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/sync_48px.png"))); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 760, 200, 50));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientRegistration.setBackground(java.awt.Color.black);
        btnClientRegistration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientRegistration.setForeground(java.awt.Color.white);
        btnClientRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_40px.png"))); // NOI18N
        btnClientRegistration.setText("Client Registration");
        btnClientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 310, 70));

        btnItemDetails.setBackground(java.awt.Color.black);
        btnItemDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnItemDetails.setForeground(java.awt.Color.white);
        btnItemDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/grinding_machine_48px.png"))); // NOI18N
        btnItemDetails.setText("  Item Details");
        btnItemDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnItemDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 310, 70));

        btnUserRegistration.setBackground(java.awt.Color.black);
        btnUserRegistration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnUserRegistration.setForeground(java.awt.Color.white);
        btnUserRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_48px.png"))); // NOI18N
        btnUserRegistration.setText("User Registration");
        btnUserRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnUserRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 310, 70));

        btnPaymentDetails.setBackground(java.awt.Color.black);
        btnPaymentDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnPaymentDetails.setForeground(java.awt.Color.white);
        btnPaymentDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnPaymentDetails.setText("Payment Details");
        btnPaymentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnPaymentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 660, 310, 70));

        jLabel2.setBackground(new java.awt.Color(72, 219, 251));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/menu_48px.png"))); // NOI18N
        jLabel2.setText("HOME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 59));

        btnClientPayment.setBackground(java.awt.Color.black);
        btnClientPayment.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientPayment.setForeground(java.awt.Color.white);
        btnClientPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnClientPayment.setText("Client Payment");
        btnClientPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 310, 70));

        btnAddorder.setBackground(java.awt.Color.black);
        btnAddorder.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnAddorder.setForeground(java.awt.Color.white);
        btnAddorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_shopping_cart_48px.png"))); // NOI18N
        btnAddorder.setText("Place Order");
        btnAddorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddorderActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 310, 70));

        btnOrderDetails2.setBackground(java.awt.Color.black);
        btnOrderDetails2.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnOrderDetails2.setForeground(java.awt.Color.white);
        btnOrderDetails2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/order_history_48px.png"))); // NOI18N
        btnOrderDetails2.setText("   Order Details");
        btnOrderDetails2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDetails2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrderDetails2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 310, 70));

        btnEmployeeRegistration.setBackground(java.awt.Color.black);
        btnEmployeeRegistration.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        btnEmployeeRegistration.setForeground(java.awt.Color.white);
        btnEmployeeRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/worker_48px.png"))); // NOI18N
        btnEmployeeRegistration.setText("Employee Registration");
        btnEmployeeRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmployeeRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 310, 70));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setBackground(new java.awt.Color(72, 219, 251));
        jLabel15.setFont(new java.awt.Font("Stencil", 3, 50)); // NOI18N
        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Visko Rental");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 680, 59));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 996, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientRegistrationActionPerformed
        new AdminClintRegistratoinView().setVisible(true);
        this.hide();

    }//GEN-LAST:event_btnClientRegistrationActionPerformed

    private void btnItemDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDetailsActionPerformed
        new AdminItemDetailView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnItemDetailsActionPerformed

    private void btnUserRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserRegistrationActionPerformed
        new AdminUserRegitrationView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnUserRegistrationActionPerformed

    private void btnPaymentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentDetailsActionPerformed
        new AdminPaymentDetailsView().setVisible(true);
    }//GEN-LAST:event_btnPaymentDetailsActionPerformed

    private void txtRedateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRedateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRedateActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new AdminDashBordView().setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void btnClientPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientPaymentActionPerformed
        new AdminClientPaymentView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClientPaymentActionPerformed

    private void btnAddorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddorderActionPerformed
        new AdminPlaceOrderView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAddorderActionPerformed

    private void btnOrderDetails2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDetails2ActionPerformed
        new AdminOrderDetailView().setVisible(true);
        this.hide();

    }//GEN-LAST:event_btnOrderDetails2ActionPerformed

    private void txtdatetimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdatetimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdatetimeActionPerformed

    private void btnRetunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetunActionPerformed
        
        try {
            Repair repair = new Repair(
                    cmbrepair.getSelectedItem().toString(),
                    txtSerailno.getText(),
                    txtdate.getText(),
                    txtQTY.getText(),
                    txtRedate.getText()
            );
            
            boolean isUpdated = RepairDetailsController.updateRepair(repair);
            
            if(isUpdated){   
                JOptionPane.showMessageDialog(this, "Updated...");
                loadAllRepair();
                
               
            } else {
                JOptionPane.showMessageDialog(this, "Update fail....");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        
    }//GEN-LAST:event_btnRetunActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyActionPerformed

    private void txtRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRepairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRepairActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String number = txtRepair.getText();
            String serial = cmbSerialno.getSelectedItem().toString();
            String date = txtdatetime.getText();
            String qty = txtqty.getText();
          
            Repair repair = new Repair(number, serial, date, qty, null);

            boolean isAdded = RepairDetailsController.AddRepair(repair);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added to Repair");
                loadAllRepair();
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (SQLException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void txtQTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQTYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQTYActionPerformed

    private void txtSerailnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerailnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerailnoActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdateActionPerformed

    private void cmbrepairItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbrepairItemStateChanged
        
       
        try {
            String repairno = cmbrepair.getSelectedItem().toString();
            Repair repair = RepairDetailsController.sarchRepair(repairno);
            txtSerailno.setText(repair.getSerial_No());
            txtdate.setText(repair.getRepair_date());
            txtQTY.setText(repair.getQty());
        } catch (SQLException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }
        

        
        
    }//GEN-LAST:event_cmbrepairItemStateChanged

    private void cmbrepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbrepairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbrepairActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        
        
        
        try {
            ArrayList<Repair> allrepair = RepairDetailsController.getAllRepair();
            DefaultTableModel dtm = (DefaultTableModel) tblRepair.getModel();
            dtm.setRowCount(0);
            for (Repair repair : allrepair) {
                Object[] rowData = {
                    repair.getRepairID(),
                    repair.getSerial_No(),
                    repair.getRepair_date(),
                    repair.getQty(),
                    repair.getReturnDATE() };
                
                dtm.addRow(rowData);
                
                
            }   } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnEmployeeRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeRegistrationActionPerformed
        new AdminEmployeeRegistrationView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnEmployeeRegistrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRepairDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRepairDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRepairDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRepairDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRepairDetailsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAddorder;
    private javax.swing.JButton btnClientPayment;
    private javax.swing.JButton btnClientRegistration;
    private javax.swing.JButton btnEmployeeRegistration;
    private javax.swing.JButton btnItemDetails;
    private javax.swing.JButton btnOrderDetails2;
    private javax.swing.JButton btnPaymentDetails;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnRetun;
    private javax.swing.JButton btnUserRegistration;
    private javax.swing.JComboBox<String> cmbSerialno;
    private javax.swing.JComboBox<String> cmbrepair;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblRepair;
    private javax.swing.JTextField txtQTY;
    private javax.swing.JTextField txtRedate;
    private javax.swing.JTextField txtRepair;
    private javax.swing.JTextField txtSerailno;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdatetime;
    private javax.swing.JTextField txtqty;
    // End of variables declaration//GEN-END:variables

    private void genarateRepairID() {

        try {
            String repairId = RepairDetailsController.generateRepairId();
            txtRepair.setText(repairId);
        } catch (SQLException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllItem() {
        try {
            ArrayList<Item> allItem = ItemDetailsController.getAllItem();
            for (Item item : allItem) {
                cmbSerialno.addItem(item.getSerial_No());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String formatDate(Date date) {

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        return sdf.format(date);

    }

    private void loadAllRepairNumber() {
        try {
            ArrayList<Repair> allrepair = RepairDetailsController.getAllItem();
            for (Repair repair : allrepair) {
                cmbrepair.addItem(repair.getRepairID());
            }   } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }
}

    private void loadAllRepair() {
       
    
     
        try {
            ArrayList<Repair> allrepair = RepairDetailsController.getAllRepair();
            DefaultTableModel dtm = (DefaultTableModel) tblRepair.getModel();
            dtm.setRowCount(0);
            for (Repair repair : allrepair) {
                Object[] rowData = {
                    repair.getRepairID(),
                    repair.getSerial_No(),
                    repair.getRepair_date(),
                    repair.getQty(),
                    repair.getReturnDATE() };
                
                dtm.addRow(rowData);
                
                
            }   } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminRepairDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    
    }
}