/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ViskoRental.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.ViskoRental.controller.EmployeeRegistrationController;
import lk.ijse.ViskoRental.controller.PaymentDetailController;
import lk.ijse.ViskoRental.controller.PlaceOrderController;
import lk.ijse.ViskoRental.controller.RepairDetailsController;
import lk.ijse.ViskoRental.model.Employee;
import lk.ijse.ViskoRental.model.Order;
import lk.ijse.ViskoRental.model.PaymentDetail;
import lk.ijse.ViskoRental.model.Repair;

/**
 *
 * @author hp
 */
public class AdminPaymentDetailsView extends javax.swing.JFrame {

    /**
     * Creates new form PaymentDetailsView
     */
    public AdminPaymentDetailsView() {
        initComponents();
        setLocationRelativeTo(null);
        genaretePaymentId();
        loadAllEmployee();
        loadAllRepairID();
        loadAllPayment();

        Date date = new Date();
        String formatDate = formatDate(date);
        txtDate.setText(formatDate);
        
        calculateIncomeSpend();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayment = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btnPayEmployee = new javax.swing.JButton();
        cmbEmpID = new javax.swing.JComboBox<>();
        txtPID = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtspend = new javax.swing.JTextField();
        jButton17 = new javax.swing.JButton();
        cmbRID = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtISpend1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtPID1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnPayRepair = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        txtprofite = new javax.swing.JTextField();
        txtincome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtallspend = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        btnprofite = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnClientRegistration = new javax.swing.JButton();
        btnRepair = new javax.swing.JButton();
        btnItemDetails = new javax.swing.JButton();
        btnUserRegistration = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnClientPayment = new javax.swing.JButton();
        btnAddorder = new javax.swing.JButton();
        btnOrderDetails = new javax.swing.JButton();
        btnEmployeeRegistration = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(41, 128, 185));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 380, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Repair ID");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 130, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Employee ID");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 100, 130, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("All Spend");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 650, 130, -1));

        tblPayment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tblPayment.setForeground(new java.awt.Color(51, 51, 255));
        tblPayment.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Payment ID", "Order ID", "Employee ID", "Repair ID", "Date", "Income", "Spend"
            }
        ));
        tblPayment.setGridColor(new java.awt.Color(102, 102, 255));
        jScrollPane1.setViewportView(tblPayment);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1290, 170));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Spend");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, 130, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Date/Time ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, 130, -1));

        jButton3.setBackground(java.awt.Color.white);
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 153, 255));
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 820, 140, -1));

        jButton4.setBackground(java.awt.Color.white);
        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 153, 255));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 820, 140, -1));

        jButton6.setBackground(java.awt.Color.white);
        jButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 153, 255));
        jButton6.setText("BACK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 820, 140, -1));

        btnPayEmployee.setBackground(new java.awt.Color(255, 255, 102));
        btnPayEmployee.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnPayEmployee.setForeground(new java.awt.Color(0, 0, 0));
        btnPayEmployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/spend48px.png"))); // NOI18N
        btnPayEmployee.setText("  PAY");
        btnPayEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayEmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 120, 200, 60));

        cmbEmpID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbEmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpIDActionPerformed(evt);
            }
        });
        jPanel1.add(cmbEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 170, 40));

        txtPID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtPID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 220, 40));

        txtDate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDate.setForeground(new java.awt.Color(51, 51, 255));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, 220, 40));

        txtspend.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtspend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtspendActionPerformed(evt);
            }
        });
        jPanel1.add(txtspend, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 220, 40));

        jButton17.setBackground(new java.awt.Color(0, 51, 255));
        jButton17.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jButton17.setForeground(java.awt.Color.white);
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/back_arrow_48px.png"))); // NOI18N
        jButton17.setText("BACK");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 740, 190, 50));

        cmbRID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(cmbRID, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 170, 40));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/worker_48px.png"))); // NOI18N
        jLabel11.setText("Pay to Employee");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 250, -1));

        txtISpend1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtISpend1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtISpend1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtISpend1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 260, 220, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 1310, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 1310, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 1210, 0));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Spend");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 100, 130, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Payment ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 130, -1));

        txtPID1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtPID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPID1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtPID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 220, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 0, 51));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/wrench_48px.png"))); // NOI18N
        jLabel13.setText("Pay to Repair");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 230, -1));

        btnPayRepair.setBackground(new java.awt.Color(255, 255, 102));
        btnPayRepair.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnPayRepair.setForeground(new java.awt.Color(0, 0, 0));
        btnPayRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/spend48px.png"))); // NOI18N
        btnPayRepair.setText("  PAY");
        btnPayRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayRepairActionPerformed(evt);
            }
        });
        jPanel1.add(btnPayRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 240, 200, 60));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 1310, 10));

        txtprofite.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtprofite.setForeground(new java.awt.Color(51, 51, 255));
        txtprofite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprofiteActionPerformed(evt);
            }
        });
        jPanel1.add(txtprofite, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 570, 210, 40));

        txtincome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtincome.setForeground(new java.awt.Color(51, 51, 255));
        txtincome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtincomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtincome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 210, 40));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Payment ID");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 130, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("All Income");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 130, -1));

        txtallspend.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtallspend.setForeground(new java.awt.Color(51, 51, 255));
        txtallspend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtallspendActionPerformed(evt);
            }
        });
        jPanel1.add(txtallspend, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 210, 40));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("All Spend");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 540, 130, -1));

        btnprofite.setBackground(new java.awt.Color(153, 153, 255));
        btnprofite.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnprofite.setForeground(new java.awt.Color(255, 51, 51));
        btnprofite.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/profit_16px.png"))); // NOI18N
        btnprofite.setText("CHECK PROFIT");
        btnprofite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprofiteActionPerformed(evt);
            }
        });
        jPanel1.add(btnprofite, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 570, 200, 40));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientRegistration.setBackground(java.awt.Color.black);
        btnClientRegistration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientRegistration.setForeground(java.awt.Color.white);
        btnClientRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_40px.png"))); // NOI18N
        btnClientRegistration.setText("Client Registration");
        btnClientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 310, 70));

        btnRepair.setBackground(java.awt.Color.black);
        btnRepair.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnRepair.setForeground(java.awt.Color.white);
        btnRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/maintenance_48px.png"))); // NOI18N
        btnRepair.setText("Repair and Maintain ");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });
        jPanel2.add(btnRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 310, 70));

        btnItemDetails.setBackground(java.awt.Color.black);
        btnItemDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnItemDetails.setForeground(java.awt.Color.white);
        btnItemDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/grinding_machine_48px.png"))); // NOI18N
        btnItemDetails.setText("  Item Details");
        btnItemDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnItemDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 310, 70));

        btnUserRegistration.setBackground(java.awt.Color.black);
        btnUserRegistration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnUserRegistration.setForeground(java.awt.Color.white);
        btnUserRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_48px.png"))); // NOI18N
        btnUserRegistration.setText("User Registration");
        btnUserRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnUserRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 310, 70));

        jLabel2.setBackground(new java.awt.Color(72, 219, 251));
        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/menu_48px.png"))); // NOI18N
        jLabel2.setText("HOME");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 59));

        btnClientPayment.setBackground(java.awt.Color.black);
        btnClientPayment.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientPayment.setForeground(java.awt.Color.white);
        btnClientPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnClientPayment.setText("Client Payment");
        btnClientPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 310, 70));

        btnAddorder.setBackground(java.awt.Color.black);
        btnAddorder.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnAddorder.setForeground(java.awt.Color.white);
        btnAddorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_shopping_cart_48px.png"))); // NOI18N
        btnAddorder.setText("Place Order");
        btnAddorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddorderActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 310, 70));

        btnOrderDetails.setBackground(java.awt.Color.black);
        btnOrderDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnOrderDetails.setForeground(java.awt.Color.white);
        btnOrderDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/order_history_48px.png"))); // NOI18N
        btnOrderDetails.setText("   Order Details");
        btnOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrderDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 720, 310, 70));

        btnEmployeeRegistration.setBackground(java.awt.Color.black);
        btnEmployeeRegistration.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        btnEmployeeRegistration.setForeground(java.awt.Color.white);
        btnEmployeeRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/worker_48px.png"))); // NOI18N
        btnEmployeeRegistration.setText("Employee Registration");
        btnEmployeeRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmployeeRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 310, 70));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(72, 219, 251));
        jLabel9.setFont(new java.awt.Font("Stencil", 3, 50)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Visko Rental");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 510, 59));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnClientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientRegistrationActionPerformed
        new AdminClintRegistratoinView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClientRegistrationActionPerformed

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        new AdminRepairDetailsView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnRepairActionPerformed

    private void btnItemDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDetailsActionPerformed
        new AdminItemDetailView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnItemDetailsActionPerformed

    private void btnUserRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserRegistrationActionPerformed
        new AdminUserRegitrationView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnUserRegistrationActionPerformed

    private void txtPIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPIDActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void txtspendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtspendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtspendActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new AdminDashBordView().setVisible(true);

    }//GEN-LAST:event_formWindowClosed

    private void btnClientPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientPaymentActionPerformed
        new AdminClientPaymentView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClientPaymentActionPerformed

    private void btnAddorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddorderActionPerformed
        new AdminPlaceOrderView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAddorderActionPerformed

    private void btnOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDetailsActionPerformed
        new AdminOrderDetailView().setVisible(true);
        this.hide();

    }//GEN-LAST:event_btnOrderDetailsActionPerformed

    private void cmbEmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmpIDActionPerformed

    private void btnPayEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayEmployeeActionPerformed
       
        JOptionPane.showMessageDialog(null, "You want to Pay for Employee",
                    "ASK TO PAY", JOptionPane.OK_CANCEL_OPTION);
        try {
            String pid = txtPID.getText();
            String orderid = null;
            String employeeid = cmbEmpID.getSelectedItem().toString();
            String repairid = null;

            String date = txtDate.getText();
            double income = 0;
            double spend = Double.parseDouble(txtspend.getText());
           
            PaymentDetail paymentdetail = new PaymentDetail(pid, orderid, employeeid, repairid, date, income, spend);

            boolean isAdded = PaymentDetailController.AddPayment(paymentdetail);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Payment is Done");
                genaretePaymentId();
                txtspend.setText(null);
                loadAllPayment();
                genaretePaymentId();
                calculateIncomeSpend();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnPayEmployeeActionPerformed

    private void txtISpend1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtISpend1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtISpend1ActionPerformed

    private void txtPID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPID1ActionPerformed

    private void btnPayRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayRepairActionPerformed
      
          JOptionPane.showMessageDialog(null, "You want to Pay for Repair",
                    "ASK TO PAY", JOptionPane.OK_CANCEL_OPTION);
        try {
            String pid = txtPID.getText();
            String orderid = null;
            String employeeid = cmbEmpID.getSelectedItem().toString();
            String repairid = null;

            String date = txtDate.getText();
            double income = 0;
            double spend = Double.parseDouble(txtISpend1.getText());
           
            PaymentDetail paymentdetail = new PaymentDetail(pid, orderid, employeeid, repairid, date, income, spend);

            boolean isAdded = PaymentDetailController.AddPayment(paymentdetail);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Payment is Done");
                genaretePaymentId();
                txtISpend1.setText(null);
                loadAllPayment();
                genaretePaymentId();
                calculateIncomeSpend();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_btnPayRepairActionPerformed

    private void btnEmployeeRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeRegistrationActionPerformed
        new AdminEmployeeRegistrationView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnEmployeeRegistrationActionPerformed

    private void txtprofiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprofiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprofiteActionPerformed

    private void txtincomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtincomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtincomeActionPerformed

    private void txtallspendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtallspendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtallspendActionPerformed

    private void btnprofiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprofiteActionPerformed
      
       double income = Double.parseDouble(txtincome.getText());
         double spend = Double.parseDouble(txtallspend.getText());
    
         
         double total= income-spend;
         txtprofite.setText(total+"");
        
    }//GEN-LAST:event_btnprofiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPaymentDetailsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddorder;
    private javax.swing.JButton btnClientPayment;
    private javax.swing.JButton btnClientRegistration;
    private javax.swing.JButton btnEmployeeRegistration;
    private javax.swing.JButton btnItemDetails;
    private javax.swing.JButton btnOrderDetails;
    private javax.swing.JButton btnPayEmployee;
    private javax.swing.JButton btnPayRepair;
    private javax.swing.JButton btnRepair;
    private javax.swing.JButton btnUserRegistration;
    private javax.swing.JButton btnprofite;
    private javax.swing.JComboBox<String> cmbEmpID;
    private javax.swing.JComboBox<String> cmbRID;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable tblPayment;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtISpend1;
    private javax.swing.JTextField txtPID;
    private javax.swing.JTextField txtPID1;
    private javax.swing.JTextField txtallspend;
    private javax.swing.JTextField txtincome;
    private javax.swing.JTextField txtprofite;
    private javax.swing.JTextField txtspend;
    // End of variables declaration//GEN-END:variables

    private void genaretePaymentId() {
        try {
            String PayID = PaymentDetailController.generatePayID();
            txtPID.setText(PayID);
            txtPID1.setText(PayID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadAllEmployee() {
        try {
            ArrayList<Employee> allEmployee = EmployeeRegistrationController.getAllEmployee();
            for (Employee employee : allEmployee) {
                cmbEmpID.addItem(employee.getEmployeeId());
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private String formatDate(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        return sdf.format(date);
    }

    private void loadAllRepairID() {
        try {
            ArrayList<Repair> allrepair = RepairDetailsController.getAllItem();
            for (Repair repair : allrepair) {
                cmbRID.addItem(repair.getRepairID());

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllPayment() {
        try {
            ArrayList<PaymentDetail> PaymentDetail = PaymentDetailController.getAllpayment();
            DefaultTableModel dtm = (DefaultTableModel) tblPayment.getModel();
            dtm.setRowCount(0);
            for ( PaymentDetail paymentdetail : PaymentDetail) {
                Object[] rowData = {
                    paymentdetail.getPaymentID(),
                    paymentdetail.getOrderID(),
                    paymentdetail.getEmployeeId(), 
                    paymentdetail.getRepairID(),
                    paymentdetail.getDate(), 
                    paymentdetail.getIncome(),
                    paymentdetail.getSpend()
                };
                dtm.addRow(rowData);
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPaymentDetailsView.class.getName()).log(Level.SEVERE, null, ex);
        }}

  

    private void calculateIncomeSpend() {
        
     DefaultTableModel dtm = (DefaultTableModel) tblPayment.getModel();

        double income = 0;
        double spend = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            income += (double) dtm.getValueAt(i, 5);
            spend += (double) dtm.getValueAt(i, 6);
        }
        txtincome.setText(income + "");
        txtallspend.setText(spend + "");
    }

    
    
    
    }
    


