/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ViskoRental.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.ViskoRental.controller.UserRegistrationController;
import lk.ijse.ViskoRental.model.SystemUser;

/**
 * @author hp
 */
public class AdminUserRegitrationView extends javax.swing.JFrame {

    private int selectedRow;

    /**
     * Creates new form AdminUserRegitrationView
     */
    public AdminUserRegitrationView() {
        initComponents();
        setLocationRelativeTo(null);
        generateUserId();
        loadALlUser();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnClientRegistration = new javax.swing.JButton();
        btnRepair = new javax.swing.JButton();
        btnItemDetails = new javax.swing.JButton();
        btnPaymentDetails = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnClientPayment = new javax.swing.JButton();
        btnAddorder = new javax.swing.JButton();
        btnOrderDetails = new javax.swing.JButton();
        btnEmployeeRegistration = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblUser = new javax.swing.JTable();
        btnSarch = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtPswrdAgain = new javax.swing.JPasswordField();
        txtpswrdNew = new javax.swing.JPasswordField();
        btnRefersh = new javax.swing.JButton();
        txtUserName1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmdUserType = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientRegistration.setBackground(java.awt.Color.black);
        btnClientRegistration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientRegistration.setForeground(java.awt.Color.white);
        btnClientRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_40px.png"))); // NOI18N
        btnClientRegistration.setText("Client Registration");
        btnClientRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 310, 70));

        btnRepair.setBackground(java.awt.Color.black);
        btnRepair.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnRepair.setForeground(java.awt.Color.white);
        btnRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/maintenance_48px.png"))); // NOI18N
        btnRepair.setText("Repair and Maintain ");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });
        jPanel2.add(btnRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 310, 70));

        btnItemDetails.setBackground(java.awt.Color.black);
        btnItemDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnItemDetails.setForeground(java.awt.Color.white);
        btnItemDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/grinding_machine_48px.png"))); // NOI18N
        btnItemDetails.setText("  Item Details");
        btnItemDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnItemDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 310, 70));

        btnPaymentDetails.setBackground(java.awt.Color.black);
        btnPaymentDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnPaymentDetails.setForeground(java.awt.Color.white);
        btnPaymentDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnPaymentDetails.setText("Payment Details");
        btnPaymentDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaymentDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnPaymentDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 730, 310, 70));

        jLabel6.setBackground(new java.awt.Color(72, 219, 251));
        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/menu_48px.png"))); // NOI18N
        jLabel6.setText("HOME");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 290, 59));

        btnClientPayment.setBackground(java.awt.Color.black);
        btnClientPayment.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientPayment.setForeground(java.awt.Color.white);
        btnClientPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnClientPayment.setText("Client Payment");
        btnClientPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 310, 70));

        btnAddorder.setBackground(java.awt.Color.black);
        btnAddorder.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnAddorder.setForeground(java.awt.Color.white);
        btnAddorder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_shopping_cart_48px.png"))); // NOI18N
        btnAddorder.setText("Place Order");
        btnAddorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddorderActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 310, 70));

        btnOrderDetails.setBackground(java.awt.Color.black);
        btnOrderDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnOrderDetails.setForeground(java.awt.Color.white);
        btnOrderDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/order_history_48px.png"))); // NOI18N
        btnOrderDetails.setText("   Order Details");
        btnOrderDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnOrderDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 640, 310, 70));

        btnEmployeeRegistration.setBackground(java.awt.Color.black);
        btnEmployeeRegistration.setFont(new java.awt.Font("Dialog", 1, 21)); // NOI18N
        btnEmployeeRegistration.setForeground(java.awt.Color.white);
        btnEmployeeRegistration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/worker_48px.png"))); // NOI18N
        btnEmployeeRegistration.setText("Employee Registration");
        btnEmployeeRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeRegistrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnEmployeeRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 310, 70));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(72, 219, 251));
        jLabel7.setFont(new java.awt.Font("Stencil", 3, 50)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Visko Rental");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 680, 59));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setForeground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(71, 71, 135));
        jLabel2.setText("User Registration");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 290, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Again");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 70, -1));

        tblUser.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tblUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "User Type", "User Name", "Passwrd New", "password Again"
            }
        ));
        tblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUser);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 1020, 150));

        btnSarch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSarch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/search_48px.png"))); // NOI18N
        btnSarch.setText("SARCH");
        btnSarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSarchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSarch, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 140, 180, 50));

        btnDelete.setBackground(new java.awt.Color(231, 76, 60));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/waste_48px.png"))); // NOI18N
        btnDelete.setText("DELELTE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 310, 180, 50));

        btnUpdate.setBackground(new java.awt.Color(230, 126, 34));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/update_user_48px.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 220, 180, 50));

        jButton18.setBackground(new java.awt.Color(0, 51, 255));
        jButton18.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jButton18.setForeground(java.awt.Color.white);
        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/back_arrow_48px.png"))); // NOI18N
        jButton18.setText("BACK");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, 190, 50));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("User Name");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 170, -1));

        txtUserId.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 260, 40));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("User Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 170, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("New");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 70, -1));

        btnOK.setBackground(new java.awt.Color(153, 153, 255));
        btnOK.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnOK.setForeground(new java.awt.Color(0, 0, 153));
        btnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/ok_48px.png"))); // NOI18N
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 400, 80, 70));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("User Type");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 170, -1));

        txtPswrdAgain.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(txtPswrdAgain, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 250, 40));

        txtpswrdNew.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jPanel1.add(txtpswrdNew, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 250, 40));

        btnRefersh.setBackground(new java.awt.Color(102, 102, 255));
        btnRefersh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRefersh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/sync_48px.png"))); // NOI18N
        btnRefersh.setText("REFRESH");
        btnRefersh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefershActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefersh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 200, 50));

        txtUserName1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtUserName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserName1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 440, 40));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("User ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 170, -1));

        cmdUserType.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmdUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "User" }));
        jPanel1.add(cmdUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 170, 40));

        btnClear.setBackground(new java.awt.Color(102, 102, 255));
        btnClear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/broom_48px.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 920, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientRegistrationActionPerformed
        new AdminClintRegistratoinView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClientRegistrationActionPerformed

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        new AdminRepairDetailsView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnRepairActionPerformed

    private void btnItemDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDetailsActionPerformed
        new AdminItemDetailView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnItemDetailsActionPerformed

    private void btnPaymentDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaymentDetailsActionPerformed
        new AdminPaymentDetailsView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnPaymentDetailsActionPerformed

    private void btnClientPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientPaymentActionPerformed
        new AdminClientPaymentView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClientPaymentActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        SystemUser systemUser = new SystemUser(txtUserId.getText(), cmdUserType.getSelectedItem().toString(), txtUserName1.getText(), txtpswrdNew.getText(), txtPswrdAgain.getText());
        try {
            boolean isUpdate = UserRegistrationController.updateUser(systemUser);
            if (isUpdate) {
                JOptionPane.showMessageDialog(this, "Update Success");
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Update fail..");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void txtUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIdActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String userid = txtUserId.getText();
        String userType = cmdUserType.getSelectedItem().toString();
        String username = txtUserName1.getText();

        String userPswrdNew = txtpswrdNew.getText();
        String userPswrdagain = txtPswrdAgain.getText();

        SystemUser systemuser = new SystemUser(userid, userType, username, userPswrdNew, userPswrdagain);
        if (!userPswrdNew.isEmpty() && !userPswrdagain.isEmpty() && userPswrdNew.equals(userPswrdagain) && !userid.isEmpty() && !username.isEmpty()) {
            try {

                boolean isAdded = UserRegistrationController.addUser(systemuser);
                if (isAdded) {
                    JOptionPane.showMessageDialog(this, "User Added");
                    clear();
                    generateUserId();
                    loadALlUser();
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (SQLException ex) {
                Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            //JOptionPane.showMessageDialog(this, "Try Again");
            JOptionPane.showMessageDialog(null, "Try Again? Enter same Password or Complete All action",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnOKActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        new AdminDashBordView().setVisible(true);

    }//GEN-LAST:event_formWindowClosed

    private void btnRefershActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefershActionPerformed
        try {
            ArrayList<SystemUser> alluser = UserRegistrationController.getAllUser();
            DefaultTableModel dtm = (DefaultTableModel) tblUser.getModel();
            dtm.setRowCount(0);
            for (SystemUser systemUser : alluser) {
                Object[] rowData = {systemUser.getUserID(), systemUser.getUserType(), systemUser.getUserName(), systemUser.getUserPasswordNew(), systemUser.getUserPasswordAgain()};
                dtm.addRow(rowData);
            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btnRefershActionPerformed

    private void txtUserName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserName1ActionPerformed
        if (txtUserName1.getText().trim().length() > 0) {
            try {
                SystemUser obj = new UserRegistrationController().getUser(txtUserName1.getText().trim());
                if (obj != null) {
                    txtUserId.setText(obj.getUserID());
                    txtpswrdNew.setText(obj.getUserPasswordNew());
                    txtPswrdAgain.setText(obj.getUserPasswordAgain());
                } else {
                    JOptionPane.showMessageDialog(this, "NO Result Found", "Warring", JOptionPane.ERROR_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Try Again? Enter User Name",
                    "PopUp4", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_txtUserName1ActionPerformed

    private void btnSarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSarchActionPerformed
        String id = txtUserId.getText();
        try {
            SystemUser systemuser = UserRegistrationController.sarchUser(id);
            if (systemuser != null) {
                txtUserName1.setText(systemuser.getUserName());
                cmdUserType.getSelectedItem().toString();
                txtpswrdNew.setText(systemuser.getUserPasswordNew());
                txtPswrdAgain.setText(systemuser.getUserPasswordAgain());

            } else {
                JOptionPane.showMessageDialog(this, "User not found...");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSarchActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String userName = txtUserName1.getText();
        try {
            boolean isDeleted = UserRegistrationController.deleteUser(userName);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Deleted..");
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Delete fail..");
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUserMouseClicked
        selectedRow = tblUser.getSelectedRow();
        txtUserId.setText(tblUser.getValueAt(selectedRow, 0).toString());
        cmdUserType.setSelectedItem(tblUser.getValueAt(selectedRow, 1).toString());
        txtUserName1.setText(tblUser.getValueAt(selectedRow, 2).toString());

        txtpswrdNew.setText(tblUser.getValueAt(selectedRow, 3).toString());
        txtPswrdAgain.setText(tblUser.getValueAt(selectedRow, 4).toString());
    }//GEN-LAST:event_tblUserMouseClicked

    private void btnAddorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddorderActionPerformed
        new AdminPlaceOrderView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnAddorderActionPerformed

    private void btnOrderDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDetailsActionPerformed
        new AdminOrderDetailView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnOrderDetailsActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEmployeeRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeRegistrationActionPerformed
        new AdminEmployeeRegistrationView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnEmployeeRegistrationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUserRegitrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUserRegitrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUserRegitrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUserRegitrationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUserRegitrationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddorder;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClientPayment;
    private javax.swing.JButton btnClientRegistration;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEmployeeRegistration;
    private javax.swing.JButton btnItemDetails;
    private javax.swing.JButton btnOK;
    private javax.swing.JButton btnOrderDetails;
    private javax.swing.JButton btnPaymentDetails;
    private javax.swing.JButton btnRefersh;
    private javax.swing.JButton btnRepair;
    private javax.swing.JButton btnSarch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmdUserType;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUser;
    private javax.swing.JPasswordField txtPswrdAgain;
    private javax.swing.JTextField txtUserId;
    private javax.swing.JTextField txtUserName1;
    private javax.swing.JPasswordField txtpswrdNew;
    // End of variables declaration//GEN-END:variables

    private void generateUserId() {
        try {
            String userid = UserRegistrationController.generateUserID();
            txtUserId.setText(userid);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void clear() {
        txtUserName1.setText(null);
        txtPswrdAgain.setText(null);
        txtpswrdNew.setText(null);
        txtUserId.setText(null);
        cmdUserType.setSelectedItem(null);
    }

    private void loadALlUser() {
        try {
            ArrayList<SystemUser> alluser = UserRegistrationController.loadAllUser();
            DefaultTableModel dtm = (DefaultTableModel) tblUser.getModel();
            dtm.setRowCount(0);
            for (SystemUser systemUser : alluser) {
                Object[] rowData = {systemUser.getUserID(), systemUser.getUserType(), systemUser.getUserName(), systemUser.getUserPasswordNew(), systemUser.getUserPasswordAgain()};
                dtm.addRow(rowData);
            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
