/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ViskoRental.view;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.ViskoRental.controller.ClientRegistrationcontrollr;
import static lk.ijse.ViskoRental.controller.ClientRegistrationcontrollr.generateClientID;
import lk.ijse.ViskoRental.controller.UserRegistrationController;
import lk.ijse.ViskoRental.model.Client;
import lk.ijse.ViskoRental.model.SystemUser;
import static org.eclipse.persistence.internal.jpa.metadata.xml.XMLEntityMappingsReader.clear;

/**
 *
 * @author hp
 */
public class clientView extends javax.swing.JPanel {

    /**
     * Creates new form clientView
     */
    private int selectedRow;

    /**
     * Creates new form ClientView
     */
    public clientView() {
        initComponents();
//        setLocationRelativeTo(null);
        generateClientID();
        loadAllUser();
        loadAllClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSarch = new javax.swing.JButton();
        txtNic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbUserID = new javax.swing.JComboBox<>();
        addClient = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        btnDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1260, 880));

        jPanel5.setBackground(java.awt.Color.white);
        jPanel5.setForeground(new java.awt.Color(255, 51, 51));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Client Address");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 180, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Client Name");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 120, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Client Contact");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 140, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Client NIC Number");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 180, -1));

        btnRefresh.setBackground(new java.awt.Color(102, 102, 255));
        btnRefresh.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/sync_48px.png"))); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel5.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 740, 200, 50));

        btnUpdate.setBackground(new java.awt.Color(230, 126, 34));
        btnUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/update_user_48px.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel5.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 220, 180, 50));

        btnSarch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSarch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/search_48px.png"))); // NOI18N
        btnSarch.setText("SARCH");
        btnSarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSarchActionPerformed(evt);
            }
        });
        jPanel5.add(btnSarch, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 180, 50));

        txtNic.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtNic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNicActionPerformed(evt);
            }
        });
        jPanel5.add(txtNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 310, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Client ID");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, -1));

        cmbUserID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel5.add(cmbUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 156, 170, 40));

        addClient.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        addClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_48px.png"))); // NOI18N
        addClient.setText("Add");
        addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClientActionPerformed(evt);
            }
        });
        jPanel5.add(addClient, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 500, 210, 50));

        txtAddress.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(txtAddress);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, 310, 70));

        tblClient.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Client ID", "Name", "Contact", "NIC Number", "Address"
            }
        ));
        tblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClient);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, 1070, 150));

        btnDelete.setBackground(new java.awt.Color(231, 76, 60));
        btnDelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/waste_48px.png"))); // NOI18N
        btnDelete.setText("DELELTE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel5.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 160, 180, 50));

        jLabel8.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(41, 128, 185));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Client Registration");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 380, 40));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("User ID");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 100, -1));

        txtID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        jPanel5.add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 310, 40));

        txtName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        jPanel5.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, 310, 40));

        txtContact.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });
        jPanel5.add(txtContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 310, 40));

        jButton7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_shopping_cart_48px.png"))); // NOI18N
        jButton7.setText("Add Order");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 430, 210, 50));

        btnClear.setBackground(new java.awt.Color(102, 102, 255));
        btnClear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/broom_48px.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel5.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 180, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1162, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        try {
            ArrayList<Client> allclient = ClientRegistrationcontrollr.getAllclient();
            DefaultTableModel dtm = (DefaultTableModel) tblClient.getModel();
            dtm.setRowCount(0);
            for (Client client : allclient) {
                Object[] rowData = {
                    client.getUserID(),
                    client.getClientID(),
                    client.getClientName(),
                    client.getClientContact(),
                    client.getClientNIC_No(),
                    client.getClientAddress()};
                dtm.addRow(rowData);

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        Client client = new Client(
                cmbUserID.getSelectedItem().toString(),
                txtID.getText(),
                txtName.getText(),
                txtContact.getText(),
                txtNic.getText(),
                txtAddress.getText());
        try {
            boolean isUpdated = ClientRegistrationcontrollr.updateClient(client);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Updated...");
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Update fail....");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSarchActionPerformed
        String id = txtName.getText();
        try {
            Client client = ClientRegistrationcontrollr.sarchClient(id);
            if (client != null) {
                cmbUserID.getSelectedItem().toString();
                txtName.setText(client.getClientName());
                txtContact.setText(client.getClientContact());
                txtNic.setText(client.getClientNIC_No());
                txtAddress.setText(client.getClientAddress());

            } else {
                JOptionPane.showMessageDialog(this, "Client not found...");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSarchActionPerformed

    private void txtNicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNicActionPerformed

    private void addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClientActionPerformed
        String userid = cmbUserID.getSelectedItem().toString();
        String id = txtID.getText();
        String name = txtName.getText();
        String contact = txtContact.getText();
        String nic = txtNic.getText();
        String address = txtAddress.getText();

        Client client = new Client(userid, id, name, contact, nic, address);
        if (!userid.isEmpty() && !id.isEmpty() && !name.isEmpty() && !contact.isEmpty() && !nic.isEmpty() && !address.isEmpty()) {
            try {
                boolean isAdded = ClientRegistrationcontrollr.AddClient(client);
                if (isAdded) {

                    JOptionPane.showMessageDialog(this, "Added Success");
                    clear();
                    generateClientID();
                    loadAllClient();

                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (SQLException ex) {
                Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Try Again? Complete All action",
                    "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_addClientActionPerformed

    private void tblClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientMouseClicked
        selectedRow = tblClient.getSelectedRow();

        cmbUserID.setSelectedItem(tblClient.getValueAt(selectedRow, 0).toString());
        txtID.setText(tblClient.getValueAt(selectedRow, 1).toString());
        txtName.setText(tblClient.getValueAt(selectedRow, 2).toString());
        txtContact.setText(tblClient.getValueAt(selectedRow, 3).toString());
        txtNic.setText(tblClient.getValueAt(selectedRow, 4).toString());
        txtAddress.setText(tblClient.getValueAt(selectedRow, 5).toString());
    }//GEN-LAST:event_tblClientMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        String clientname = txtName.getText();
        try {
            boolean isDeleted = ClientRegistrationcontrollr.deleteClient(clientname);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Deleted....");
                clear();
            } else {
                JOptionPane.showMessageDialog(this, "Delete fail...");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed

    }//GEN-LAST:event_txtIDActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        if (txtName.getText().trim().length() > 0) {
            try {
                Client obj = new ClientRegistrationcontrollr().getClient(txtName.getText().trim());
                if (obj != null) {
                    cmbUserID.setSelectedItem(obj.getUserID());
                    txtID.setText(obj.getClientID());
                    txtContact.setText(obj.getClientContact());
                    txtNic.setText(obj.getClientNIC_No());
                    txtAddress.setText(obj.getClientAddress());
                } else {
                    JOptionPane.showMessageDialog(this, "NO Result Found", "Warring", JOptionPane.ERROR_MESSAGE);
                }

            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminUserRegitrationView.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Try Again? Client Name",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_txtNameActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        new AdminPlaceOrderView().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clear();;
    }//GEN-LAST:event_btnClearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addClient;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSarch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbUserID;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClient;
    private javax.swing.JTextPane txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNic;
    // End of variables declaration//GEN-END:variables

    private void generateClientID() {
        try {
            String clientId = ClientRegistrationcontrollr.generateClientID();
            txtID.setText(clientId);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllUser() {
        try {
            ArrayList<SystemUser> alluser = UserRegistrationController.loadAllUser();

            for (SystemUser systemUser : alluser) {
                cmbUserID.addItem(systemUser.getUserID());

            }

        } catch (SQLException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllClient() {
        try {
            ArrayList<Client> allclient = ClientRegistrationcontrollr.getAllclient();
            DefaultTableModel dtm = (DefaultTableModel) tblClient.getModel();
            dtm.setRowCount(0);
            for (Client client : allclient) {
                Object[] rowData = {client.getUserID(), client.getClientID(), client.getClientName(), client.getClientContact(), client.getClientNIC_No(), client.getClientAddress()};
                dtm.addRow(rowData);
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClintRegistratoinView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void clear() {
        cmbUserID.setSelectedItem(null);
        txtName.setText(null);
        txtID.setText(null);
        txtAddress.setText(null);
        txtNic.setText(null);
        txtContact.setText(null);

    }
}
