/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ViskoRental.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.ViskoRental.controller.ClientRegistrationcontrollr;
import lk.ijse.ViskoRental.controller.OrderDetailsController;
import lk.ijse.ViskoRental.controller.PaymentDetailController;
import lk.ijse.ViskoRental.controller.PlaceOrderController;
import lk.ijse.ViskoRental.model.Client;
import lk.ijse.ViskoRental.model.Order;
import lk.ijse.ViskoRental.model.OrderDetail;
import lk.ijse.ViskoRental.model.PaymentDetail;

/**
 *
 * @author hp
 */
public class ClientPayment extends javax.swing.JPanel {
 private int selectedRow;
    /**
     * Creates new form ClientPayment
     */
    public ClientPayment() {
         initComponents();
       // setLocationRelativeTo(null);

        Date date = new Date();
        String formatDate = formatDate(date);
        txtreturn.setText(formatDate);
        txtDatePay.setText(formatDate);
        
        
        genaretePaymentID();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblorderDetails = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnreturn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtreturn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtClientName = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        btnSarch = new javax.swing.JButton();
        btngetTotal = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblorder = new javax.swing.JTable();
        txtPayment = new javax.swing.JTextField();
        txtDayCost = new javax.swing.JTextField();
        txtdys = new javax.swing.JTextField();
        txttotalpayment = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtExtr = new javax.swing.JTextField();
        bntPay = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtPymnetID = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDatePay = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1260, 880));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(26, 188, 156));
        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Item Return And Payment");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 470, -1));

        tblorderDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblorderDetails.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tblorderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Serial Number", "Qty", "Deposite", "Return Date", "Totat day Cost"
            }
        ));
        tblorderDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblorderDetailsMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tblorderDetails);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 1190, 120));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Day");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 640, 60, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("One Item Day Cost");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 640, 170, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/samana_sign_48px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 670, 50, -1));

        btnreturn.setBackground(new java.awt.Color(153, 153, 255));
        btnreturn.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnreturn.setForeground(new java.awt.Color(0, 0, 153));
        btnreturn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/return_48px.png"))); // NOI18N
        btnreturn.setText("Item Return");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        jPanel1.add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 200, 60));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Client Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 120, -1));

        txtreturn.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreturnActionPerformed(evt);
            }
        });
        jPanel1.add(txtreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 560, 310, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Deposite");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 640, 90, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Return Date/Time");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 570, 170, -1));

        txtClientName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 310, 40));

        tblClient.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblClient.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User ID", "Client Id", "Client Name", "Client Contact", "Client NIC", "Client Address"
            }
        ));
        tblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tblClient);

        jPanel1.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 1190, 120));

        btnSarch.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSarch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/search_48px.png"))); // NOI18N
        btnSarch.setText("SARCH");
        btnSarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSarchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSarch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 90, 180, 50));

        btngetTotal.setBackground(new java.awt.Color(0, 204, 204));
        btngetTotal.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btngetTotal.setForeground(new java.awt.Color(0, 0, 0));
        btngetTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/bill_48px.png"))); // NOI18N
        btngetTotal.setText("Get Total");
        btngetTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngetTotalActionPerformed(evt);
            }
        });
        jPanel1.add(btngetTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 610, 200, 50));

        tblorder.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblorder.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        tblorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Client ID", "Employee ID", "Order Date"
            }
        ));
        tblorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblorderMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tblorder);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 1190, 120));

        txtPayment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtPayment.setForeground(new java.awt.Color(255, 0, 0));
        txtPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(txtPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 200, 40));

        txtDayCost.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtDayCost.setForeground(new java.awt.Color(255, 0, 0));
        txtDayCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayCostActionPerformed(evt);
            }
        });
        jPanel1.add(txtDayCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 190, 40));

        txtdys.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jPanel1.add(txtdys, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 670, 70, 40));

        txttotalpayment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txttotalpayment.setForeground(new java.awt.Color(0, 0, 255));
        jPanel1.add(txttotalpayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 660, 200, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Discount ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 640, -1, -1));

        txtdiscount.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtdiscount.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(txtdiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 670, 150, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Exater ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 640, -1, -1));

        txtExtr.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtExtr.setForeground(new java.awt.Color(153, 153, 255));
        jPanel1.add(txtExtr, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 670, 150, 40));

        bntPay.setBackground(new java.awt.Color(255, 255, 102));
        bntPay.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        bntPay.setForeground(new java.awt.Color(0, 0, 0));
        bntPay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/income48px.png"))); // NOI18N
        bntPay.setText("  PAY");
        bntPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntPayActionPerformed(evt);
            }
        });
        jPanel1.add(bntPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 780, 200, 60));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Date/Time");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 750, 110, 30));

        txtPymnetID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtPymnetID.setForeground(new java.awt.Color(0, 0, 204));
        txtPymnetID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPymnetIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtPymnetID, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 790, 180, 40));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Payment ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 750, 110, 30));

        txtDatePay.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtDatePay.setForeground(new java.awt.Color(0, 0, 204));
        jPanel1.add(txtDatePay, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 790, 230, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1378, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblorderDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblorderDetailsMouseClicked

    }//GEN-LAST:event_tblorderDetailsMouseClicked

    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        DefaultTableModel dtm = (DefaultTableModel) tblorderDetails.getModel();
        String orderid = null;
        String serialno = null;
        String qty = null;
        double deposite = 0;
        double day = 0;
        boolean isUpdated = false;
        String date = txtreturn.getText();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            try {
                orderid = tblorderDetails.getValueAt(i, 0).toString();
                serialno = tblorderDetails.getValueAt(i, 1).toString();
                qty = tblorderDetails.getValueAt(i, 2).toString();
                deposite = (Double) tblorderDetails.getValueAt(i, 3);
                day = (Double) tblorderDetails.getValueAt(i, 5);

                OrderDetail orderdetail = new OrderDetail(orderid, serialno, qty, deposite, date, day);

                isUpdated = OrderDetailsController.updateOrders(orderdetail);
                if (isUpdated) {
                    JOptionPane.showMessageDialog(this, "Item Is Return And Update Stock");

                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnreturnActionPerformed

    private void txtreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreturnActionPerformed

    private void txtClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientNameActionPerformed

    }//GEN-LAST:event_txtClientNameActionPerformed

    private void tblClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientMouseClicked
        try {
            selectedRow = tblClient.getSelectedRow();
            String orderid = tblClient.getValueAt(selectedRow, 1).toString();

            ArrayList<Order> allOrder = PlaceOrderController.sarchOrderId(orderid);

            DefaultTableModel dtm = (DefaultTableModel) tblorder.getModel();
            dtm.setRowCount(0);
            for (Order order : allOrder) {
                Object[] rowData = {
                    order.getOrderID(),
                    order.getClientID(),
                    order.getEmployeeId(),
                    order.getOrderDate()};
                dtm.addRow(rowData);

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblClientMouseClicked

    private void btnSarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSarchActionPerformed
        try {
            String name = txtClientName.getText();

            ArrayList<Client> allclient = ClientRegistrationcontrollr.sarchClientName(name);

            DefaultTableModel dtm = (DefaultTableModel) tblClient.getModel();
            dtm.setRowCount(0);
            for (Client client : allclient) {
                Object[] rowData = {
                    client.getUserID(),
                    client.getClientID(),
                    client.getClientName(),
                    client.getClientContact(),
                    client.getClientNIC_No(),
                    client.getClientAddress()};
                dtm.addRow(rowData);

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSarchActionPerformed

    private void btngetTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngetTotalActionPerformed
        calculateTotalPayment();
    }//GEN-LAST:event_btngetTotalActionPerformed

    private void tblorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblorderMouseClicked
        try {

            selectedRow = tblorder.getSelectedRow();
            String orderid = tblorder.getValueAt(selectedRow, 0).toString();

            ArrayList<OrderDetail> allOrderDetail = OrderDetailsController.sarchOrderetail(orderid);

            DefaultTableModel dtm = (DefaultTableModel) tblorderDetails.getModel();
            dtm.setRowCount(0);
            for (OrderDetail orderdetail : allOrderDetail) {
                Object[] rowData = {
                    orderdetail.getOrderID(),
                    orderdetail.getSerial_No(),
                    orderdetail.getQty(),
                    orderdetail.getDeposite_on_hand(),
                    orderdetail.getRetrun_date(),
                    orderdetail.getTotalDayCost()

                };

                dtm.addRow(rowData);
                calculateTotalValue();

            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblorderMouseClicked

    private void txtPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPaymentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPaymentActionPerformed

    private void txtDayCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayCostActionPerformed

    private void bntPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntPayActionPerformed

        try {
            String pid = txtPymnetID.getText();
            String orderid = tblorderDetails.getValueAt(0, 0).toString();
            String empid = null;
            String rid = null;
            String date = txtDatePay.getText();
            double income = Double.parseDouble(txttotalpayment.getText());
            double spend = 0;

            PaymentDetail paymentdetail = new PaymentDetail(pid, orderid, empid, rid, date, income, spend);

            boolean isAdded = PaymentDetailController.AddPayment(paymentdetail);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Payment is Done");

               
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_bntPayActionPerformed

    private void txtPymnetIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPymnetIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPymnetIDActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntPay;
    private javax.swing.JButton btnSarch;
    private javax.swing.JButton btngetTotal;
    private javax.swing.JButton btnreturn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable tblClient;
    private javax.swing.JTable tblorder;
    private javax.swing.JTable tblorderDetails;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtDatePay;
    private javax.swing.JTextField txtDayCost;
    private javax.swing.JTextField txtExtr;
    private javax.swing.JTextField txtPayment;
    private javax.swing.JTextField txtPymnetID;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtdys;
    private javax.swing.JTextField txtreturn;
    private javax.swing.JTextField txttotalpayment;
    // End of variables declaration//GEN-END:variables

 private String formatDate(Date date) {

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        return sdf.format(date);

    }

    private void calculateTotalValue() {

        DefaultTableModel dtm = (DefaultTableModel) tblorderDetails.getModel();

        double total = 0;
        double day = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            total += (double) dtm.getValueAt(i, 3);
            day += (double) dtm.getValueAt(i, 5);
        }
        txtDayCost.setText(day + "");
        txtPayment.setText(total + "");
    }

    private void calculateTotalPayment() {
        double dayCost = Double.parseDouble(txtDayCost.getText());
        double deposite = Double.parseDouble(txtPayment.getText());
        int days = Integer.parseInt(txtdys.getText());
        double extr = Double.parseDouble(txtExtr.getText());
        double discount = Double.parseDouble(txtdiscount.getText());

        double totalpay = dayCost * days - deposite + extr - discount;
        txttotalpayment.setText(totalpay + "");

    }

    private void genaretePaymentID() {
        try {
            String PayID = PaymentDetailController.generatePayID();
            txtPymnetID.setText(PayID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminClientPaymentView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


}
