/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lk.ijse.ViskoRental.view;

import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import lk.ijse.ViskoRental.controller.ClientRegistrationcontrollr;
import lk.ijse.ViskoRental.controller.EmployeeRegistrationController;
import lk.ijse.ViskoRental.controller.ItemDetailsController;
import lk.ijse.ViskoRental.controller.PlaceOrderController;
import lk.ijse.ViskoRental.model.Client;
import lk.ijse.ViskoRental.model.Employee;
import lk.ijse.ViskoRental.model.Item;
import lk.ijse.ViskoRental.model.Order;
import lk.ijse.ViskoRental.model.OrderDetail;

/**
 *
 * @author hp
 */
public class UserPlaceDetailsView extends javax.swing.JFrame {

    /**
     * Creates new form UserPlaceDetailsView
     */
    public UserPlaceDetailsView() {
        initComponents();
        setLocationRelativeTo(null);

        Date date = new Date();
        String formatDate = formatDate(date);
        txtDate.setText(formatDate);
        
      
        loadAllClient();
        loadAllItem();
        loadAllEmployee();

        genarateOrderId();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnClientRegitration = new javax.swing.JButton();
        btnRepair = new javax.swing.JButton();
        btnItemDetails = new javax.swing.JButton();
        btnClinetPayment = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton19 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        txtClientName = new javax.swing.JTextField();
        txtOrder = new javax.swing.JTextField();
        btnPlaceOrder = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtDay = new javax.swing.JTextField();
        txtDeposit = new javax.swing.JTextField();
        txtqtyonhand = new javax.swing.JTextField();
        cmbserialNo = new javax.swing.JComboBox<>();
        cmbEmpId = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtBrandName2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtqty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbClientid = new javax.swing.JComboBox<>();
        txtDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbIItemDetails = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        txtPaymnet = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnClientRegitration.setBackground(java.awt.Color.black);
        btnClientRegitration.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClientRegitration.setForeground(java.awt.Color.white);
        btnClientRegitration.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_user_male_40px.png"))); // NOI18N
        btnClientRegitration.setText("Client Registration");
        btnClientRegitration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientRegitrationActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientRegitration, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 310, 70));

        btnRepair.setBackground(java.awt.Color.black);
        btnRepair.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnRepair.setForeground(java.awt.Color.white);
        btnRepair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/maintenance_48px.png"))); // NOI18N
        btnRepair.setText("Repair and Maintain ");
        btnRepair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepairActionPerformed(evt);
            }
        });
        jPanel2.add(btnRepair, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 310, 70));

        btnItemDetails.setBackground(java.awt.Color.black);
        btnItemDetails.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnItemDetails.setForeground(java.awt.Color.white);
        btnItemDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/grinding_machine_48px.png"))); // NOI18N
        btnItemDetails.setText("  Item Details");
        btnItemDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnItemDetailsActionPerformed(evt);
            }
        });
        jPanel2.add(btnItemDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 310, 70));

        btnClinetPayment.setBackground(java.awt.Color.black);
        btnClinetPayment.setFont(new java.awt.Font("Dialog", 1, 22)); // NOI18N
        btnClinetPayment.setForeground(java.awt.Color.white);
        btnClinetPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/paper_money_48px.png"))); // NOI18N
        btnClinetPayment.setText("Client Payment");
        btnClinetPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClinetPaymentActionPerformed(evt);
            }
        });
        jPanel2.add(btnClinetPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 310, 70));

        jLabel5.setBackground(new java.awt.Color(72, 219, 251));
        jLabel5.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/menu_48px.png"))); // NOI18N
        jLabel5.setText("  HOME");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 290, 59));

        jButton19.setBackground(java.awt.Color.black);
        jButton19.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jButton19.setForeground(java.awt.Color.white);
        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/go_back_48px.png"))); // NOI18N
        jButton19.setText("Log Out");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 790, 200, 50));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setBackground(new java.awt.Color(72, 219, 251));
        jLabel10.setFont(new java.awt.Font("Stencil", 3, 50)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Visko Rental");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 562, 59));

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Small", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Place Order ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Order ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Client Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 80, 120, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Client ID");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 90, 80, -1));

        jButton17.setBackground(new java.awt.Color(0, 51, 255));
        jButton17.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        jButton17.setForeground(java.awt.Color.white);
        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/back_arrow_48px.png"))); // NOI18N
        jButton17.setText("BACK");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 790, 190, 50));

        txtClientName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtClientName.setForeground(new java.awt.Color(255, 51, 51));
        txtClientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClientNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtClientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 130, 310, 40));

        txtOrder.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtOrder.setForeground(new java.awt.Color(255, 51, 51));
        txtOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 40));

        btnPlaceOrder.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnPlaceOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_shopping_cart_48px.png"))); // NOI18N
        btnPlaceOrder.setText("Add Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });
        jPanel1.add(btnPlaceOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 780, 210, 50));

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setForeground(new java.awt.Color(255, 253, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Employee ID");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 150, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("How much on deposite");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 80, 220, 30));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Brand Name");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, 110, 30));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Qty on Hand");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, 30));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("Per Day Cost");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 150, 30));

        txtDay.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDayActionPerformed(evt);
            }
        });
        jPanel4.add(txtDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 170, 40));

        txtDeposit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtDeposit.setForeground(new java.awt.Color(0, 0, 204));
        txtDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDepositActionPerformed(evt);
            }
        });
        jPanel4.add(txtDeposit, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 220, 40));

        txtqtyonhand.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtqtyonhand.setForeground(new java.awt.Color(0, 0, 204));
        txtqtyonhand.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtqtyonhand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyonhandActionPerformed(evt);
            }
        });
        jPanel4.add(txtqtyonhand, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 170, 40));

        cmbserialNo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbserialNo.setForeground(new java.awt.Color(255, 51, 51));
        cmbserialNo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbserialNoItemStateChanged(evt);
            }
        });
        cmbserialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbserialNoActionPerformed(evt);
            }
        });
        jPanel4.add(cmbserialNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 170, 40));

        cmbEmpId.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbEmpId.setForeground(new java.awt.Color(255, 0, 0));
        cmbEmpId.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEmpIdItemStateChanged(evt);
            }
        });
        cmbEmpId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEmpIdActionPerformed(evt);
            }
        });
        jPanel4.add(cmbEmpId, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 170, 40));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Serial Number");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 0, 150, 30));

        txtItemName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });
        jPanel4.add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 270, 40));

        txtBrandName2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtBrandName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandName2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtBrandName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 250, 40));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Item Name");
        jPanel4.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 110, 30));

        txtqty.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtqty.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 110, 270, 40));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Qty");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 110, 30));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 1240, -1));

        cmbClientid.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbClientid.setForeground(new java.awt.Color(255, 51, 51));
        cmbClientid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbClientidItemStateChanged(evt);
            }
        });
        cmbClientid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClientidActionPerformed(evt);
            }
        });
        jPanel1.add(cmbClientid, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 170, 40));

        txtDate.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtDate.setForeground(new java.awt.Color(0, 0, 204));
        txtDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDateActionPerformed(evt);
            }
        });
        jPanel1.add(txtDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 230, 40));

        tbIItemDetails.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tbIItemDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serial Number", "Item Day COst", "Qty", "Deposite", "Total Deposite", "Total Day Cost"
            }
        ));
        tbIItemDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbIItemDetailsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbIItemDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 1180, 180));

        btnAdd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/add_48px.png"))); // NOI18N
        btnAdd.setText("ADD ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 380, 180, 50));

        btnClear.setBackground(new java.awt.Color(102, 102, 255));
        btnClear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/ijse/ViskoRental/icon/broom_48px.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 170, 50));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1310, 30));

        txtPaymnet.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        txtPaymnet.setForeground(new java.awt.Color(255, 0, 51));
        jPanel1.add(txtPaymnet, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, 280, 40));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("Totale Deposite");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, 170, 30));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setText("Order Date/Time");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 200, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClientRegitrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientRegitrationActionPerformed
        new UserClinetRegistrationView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClientRegitrationActionPerformed

    private void btnRepairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepairActionPerformed
        new UserRepairDetailView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnRepairActionPerformed

    private void btnItemDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnItemDetailsActionPerformed
        new UserItemDetailsView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnItemDetailsActionPerformed

    private void btnClinetPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClinetPaymentActionPerformed
        new UserClientPaymentView().setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnClinetPaymentActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void txtClientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClientNameActionPerformed

    private void txtOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        String orderId = txtOrder.getText();
        String clientid = (String) cmbClientid.getSelectedItem();
        String employeid = (String) cmbEmpId.getSelectedItem();
        String orderDate = txtDate.getText();
        ArrayList<OrderDetail> orderDetailList = new ArrayList<>();
        DefaultTableModel dtm = (DefaultTableModel) tbIItemDetails.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            String serialNo = (String) dtm.getValueAt(i, 0);
            String  qty = String.valueOf(dtm.getValueAt(i, 2));
            double deposit = (double) dtm.getValueAt(i, 3);
            double day=(double) dtm.getValueAt(i, 5);
            OrderDetail orderdetail = new OrderDetail(orderId, serialNo, qty, deposit, null, day);
            orderDetailList.add(orderdetail);
        }
        Order order = new Order(orderId, clientid, employeid, orderDate, orderDetailList);
        try {
            boolean isAdded = PlaceOrderController.addOrder(order);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Success");
                new UserDshBordView().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Added Fail");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void txtDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDayActionPerformed

    private void txtDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDepositActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDepositActionPerformed

    private void txtqtyonhandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyonhandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtyonhandActionPerformed

    private void cmbserialNoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbserialNoItemStateChanged

        try {
            String serialno = cmbserialNo.getSelectedItem().toString();
            Item item = ItemDetailsController.sarchItem(serialno);
            txtBrandName2.setText(item.getBrand_name());
            txtItemName.setText(item.getItem_name());

            txtqtyonhand.setText(item.getQty_On_Hand());
            txtDay.setText(item.getPer_cost_day() + "");

            txtDeposit.setText(item.getDeposite() + "");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmbserialNoItemStateChanged

    private void cmbserialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbserialNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbserialNoActionPerformed

    private void cmbEmpIdItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEmpIdItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmpIdItemStateChanged

    private void cmbEmpIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEmpIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEmpIdActionPerformed

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void txtBrandName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandName2ActionPerformed

    private void cmbClientidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbClientidItemStateChanged

        try {
            String clientID = cmbClientid.getSelectedItem().toString();
            Client client = ClientRegistrationcontrollr.sarchClient(clientID);
            txtClientName.setText(client.getClientName());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_cmbClientidItemStateChanged

    private void cmbClientidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClientidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClientidActionPerformed

    private void txtDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDateActionPerformed

    private void tbIItemDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbIItemDetailsMouseClicked

    }//GEN-LAST:event_tbIItemDetailsMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        DefaultTableModel model = (DefaultTableModel) tbIItemDetails.getModel();
        int qty = Integer.parseInt(txtqty.getText());
        double dayCost= Double.parseDouble(txtDay.getText());
        double deposite = Double.parseDouble(txtDeposit.getText());
        double total = qty * deposite;
        double totalday=qty*dayCost;

        int rowIndex = isAlreadyExists(cmbserialNo.getSelectedItem().toString());

        if (rowIndex == -1) {
            Object[] rowData = {
                cmbserialNo.getSelectedItem().toString(),
                dayCost,
                qty,
                deposite,
                total,
                totalday
            };
            model.addRow(rowData);
        } else {
            qty += (int) model.getValueAt(rowIndex, 2);
            total = qty * deposite;
            totalday=qty*dayCost;
            tbIItemDetails.setValueAt(qty, rowIndex, 2);
            tbIItemDetails.setValueAt(total, rowIndex, 4);
            tbIItemDetails.setValueAt(totalday, rowIndex, 5);
        }

        calculateTotalValue();
        cmbserialNo.requestFocus();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed

        int selectedRow = tbIItemDetails.getSelectedRow();

        if (selectedRow == -1) {
            return;
        }

        DefaultTableModel dtm = (DefaultTableModel) tbIItemDetails.getModel();
        dtm.removeRow(selectedRow);

        calculateTotalValue();

    }//GEN-LAST:event_btnClearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPlaceDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPlaceDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPlaceDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPlaceDetailsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPlaceDetailsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnClientRegitration;
    private javax.swing.JButton btnClinetPayment;
    private javax.swing.JButton btnItemDetails;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JButton btnRepair;
    private javax.swing.JComboBox<String> cmbClientid;
    private javax.swing.JComboBox<String> cmbEmpId;
    private javax.swing.JComboBox<String> cmbserialNo;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton19;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tbIItemDetails;
    private javax.swing.JTextField txtBrandName2;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtDeposit;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtOrder;
    private javax.swing.JTextField txtPaymnet;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txtqtyonhand;
    // End of variables declaration//GEN-END:variables

 private String formatDate(Date date) {
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
        return sdf.format(date);
        
        
    }

    private void loadAllClient() {
        try {
            ArrayList<Client> allClient = ClientRegistrationcontrollr.getAllclient();
            for (Client client : allClient) {
                cmbClientid.addItem(client.getClientID());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadAllItem() {
        try {
            ArrayList<Item> allItem = ItemDetailsController.getAllItem();
            for (Item item : allItem) {
                cmbserialNo.addItem(item.getSerial_No());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void loadAllEmployee() {
        try {
            ArrayList<Employee> allEmployee = EmployeeRegistrationController.getAllEmployee();
            for (Employee employee : allEmployee) {
                cmbEmpId.addItem(employee.getEmployeeId());
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void genarateOrderId() {
        try {
            String orderid = PlaceOrderController.genarateOrderId();
            txtOrder.setText(orderid);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(AdminPlaceOrderView.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private int isAlreadyExists(String serialNo) {

        DefaultTableModel dtm = (DefaultTableModel) tbIItemDetails.getModel();

        for (int i = 0; i < dtm.getRowCount(); i++) {
            String code = (String) dtm.getValueAt(i, 0);
            if (code.equals(serialNo)) {
                return i;
            }
        }

        return -1;

    }

    private void calculateTotalValue() {

        DefaultTableModel dtm = (DefaultTableModel) tbIItemDetails.getModel();

        double total = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            total += (double) dtm.getValueAt(i, 4);
        }

        txtPaymnet.setText(total + "");
    }

    



}
